#:schema https://www.schemastore.org/treefmt.json

[formatter.go]
command = "gofmt"
includes = ["*.go"]

[formatter.biome]
command = "biome"
options = ["format", "--write"]
includes = ["*.js", "*.ts", "*.html", "*.css"]

[formatter.buf]
command = "buf"
options = ["format", "--write"]
includes = ["*.proto"]

[formatter.nix]
command = "nixfmt"
includes = ["*.nix"]

[formatter.toml]
command = "tombi"
options = ["format"]
includes = ["*.toml"]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = ["*.yaml", "*.json", "*.md"]
