name: check

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}

# yaml-language-server-disable is not allowed
enable-openid-connect: true

jobs:
  check:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@8cfbe9e5d4eef03c557a70763c90af7ff4aafe67 # v1.46.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}

      - name: Check
        run: nix flake check
