name: release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

concurrency:
  group: release

# yaml-language-server-disable is not allowed
enable-openid-connect: true

jobs:
  linux:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: write
      packages: write
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@8cfbe9e5d4eef03c557a70763c90af7ff4aafe67 # v1.46.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          fetch_depth: 0
          shell: release

      - name: Release to Forgejo
        run: flake-release
        env:
          REGISTRY: trev.zip
          REGISTRY_USERNAME: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ secrets.RENOVATE_TOKEN }}
          PACKAGES: |
            images.x86_64-linux.default.aarch64-unknown-linux-musl
            images.x86_64-linux.default.armv7l-unknown-linux-musleabihf
            images.x86_64-linux.default.x86_64-unknown-linux-musl
            packages.x86_64-linux.default.aarch64-unknown-linux-musl
            packages.x86_64-linux.default.armv7l-unknown-linux-musleabihf
            packages.x86_64-linux.default.x86_64-unknown-linux-musl
            packages.x86_64-linux.default.x86_64-w64-mingw32
