name: update

on:
  schedule:
    - cron: "0 * * * *" # once every hour
  workflow_dispatch:

# yaml-language-server-disable is not allowed
enable-openid-connect: true

jobs:
  renovate:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
    steps:
      - id: init
        name: Initialize
        uses: spotdemo4/nix-init@8cfbe9e5d4eef03c557a70763c90af7ff4aafe67 # v1.46.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          shell: update

      - name: Renovate
        run: renovate
        env:
          RENOVATE_CONFIG_FILE: .forgejo/renovate.json
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          RENOVATE_GITHUB_COM_TOKEN: ${{ secrets.GH_TOKEN }}
          LOG_LEVEL: ${{ runner.debug == '1' && 'debug' || 'info' }}
