// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: number/v1/service.proto

package numberv1connect

import (
	connect "connectrpc.com/connect/v2"
	context "context"
	sync "sync"
	v1 "trev.zip/template/stack/server/connect/number/v1"
)

const (
	// NumberServiceName is the fully-qualified name of the NumberService service.
	NumberServiceName = "number.v1.NumberService"
)

// These constants are the procedure names of the RPCs defined in this package. They're exposed at
// runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// NumberServiceAddProcedure is the procedure name of the NumberService's Add RPC.
	NumberServiceAddProcedure = "/number.v1.NumberService/Add"
	// NumberServiceListProcedure is the procedure name of the NumberService's List RPC.
	NumberServiceListProcedure = "/number.v1.NumberService/List"
	// NumberServiceSummaryProcedure is the procedure name of the NumberService's Summary RPC.
	NumberServiceSummaryProcedure = "/number.v1.NumberService/Summary"
	// NumberServiceTimeSeriesProcedure is the procedure name of the NumberService's TimeSeries RPC.
	NumberServiceTimeSeriesProcedure = "/number.v1.NumberService/TimeSeries"
	// NumberServiceDistributionProcedure is the procedure name of the NumberService's Distribution RPC.
	NumberServiceDistributionProcedure = "/number.v1.NumberService/Distribution"
	// NumberServiceTopNamesProcedure is the procedure name of the NumberService's TopNames RPC.
	NumberServiceTopNamesProcedure = "/number.v1.NumberService/TopNames"
)

var (
	numberServiceAddSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v1.File_number_v1_service_proto.Services().ByName("NumberService").Methods().ByName("Add"),
			Procedure:  NumberServiceAddProcedure,
		}
	})
	numberServiceListSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeServer,
			Schema:     v1.File_number_v1_service_proto.Services().ByName("NumberService").Methods().ByName("List"),
			Procedure:  NumberServiceListProcedure,
		}
	})
	numberServiceSummarySpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v1.File_number_v1_service_proto.Services().ByName("NumberService").Methods().ByName("Summary"),
			Procedure:  NumberServiceSummaryProcedure,
		}
	})
	numberServiceTimeSeriesSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v1.File_number_v1_service_proto.Services().ByName("NumberService").Methods().ByName("TimeSeries"),
			Procedure:  NumberServiceTimeSeriesProcedure,
		}
	})
	numberServiceDistributionSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v1.File_number_v1_service_proto.Services().ByName("NumberService").Methods().ByName("Distribution"),
			Procedure:  NumberServiceDistributionProcedure,
		}
	})
	numberServiceTopNamesSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v1.File_number_v1_service_proto.Services().ByName("NumberService").Methods().ByName("TopNames"),
			Procedure:  NumberServiceTopNamesProcedure,
		}
	})
)

// NumberServiceClient is a client for the number.v1.NumberService service.
type NumberServiceClient interface {
	// Records a named value and returns the sum of all stored numbers, not just this name or user.
	Add(context.Context, *v1.AddRequest) (*v1.AddResponse, error)
	// Streams one response per matching item, newest inserted first. An empty result sends no messages.
	// Name filtering uses a substring match; number and timestamp bounds are inclusive.
	List(context.Context, *v1.ListRequest) (NumberServiceListClientStream, error)
	// Returns count, sum, average, minimum, maximum, and distinct-name count for the selected time range.
	// All aggregates are zero when no items match.
	Summary(context.Context, *v1.SummaryRequest) (*v1.SummaryResponse, error)
	// Returns counts, sums, and averages in ascending UTC time buckets. Empty buckets are omitted.
	// Weeks begin on Sunday; months begin on the first day.
	TimeSeries(context.Context, *v1.TimeSeriesRequest) (*v1.TimeSeriesResponse, error)
	// Groups values into approximately equal-width buckets over the observed range, including empty buckets.
	// No matching items produce no buckets; identical values produce a single bucket.
	Distribution(context.Context, *v1.DistributionRequest) (*v1.DistributionResponse, error)
	// Ranks names by item count, then total value, both descending, up to the requested limit.
	TopNames(context.Context, *v1.TopNamesRequest) (*v1.TopNamesResponse, error)
}

// NewNumberServiceClient constructs a client for the number.v1.NumberService service. Multiple
// service clients may share a single connect.Client.
func NewNumberServiceClient(client *connect.Client) NumberServiceClient {
	return &numberServiceClient{client: client}
}

// NumberServiceListClientStream is the client stream for the NumberService's List RPC.
type NumberServiceListClientStream struct {
	stream connect.ClientStream
}

// Receive returns the next response message from the server.
func (s NumberServiceListClientStream) Receive() (*v1.ListResponse, error) {
	var res v1.ListResponse
	if err := s.stream.Receive(&res); err != nil {
		return nil, err
	}
	return &res, nil
}

// Close releases the stream's resources. It is idempotent and is typically deferred to clean up a
// stream abandoned before io.EOF.
func (s NumberServiceListClientStream) Close() error {
	return s.stream.Close()
}

// NumberServiceHandler is an implementation of the number.v1.NumberService service.
type NumberServiceHandler interface {
	// Records a named value and returns the sum of all stored numbers, not just this name or user.
	Add(context.Context, *v1.AddRequest) (*v1.AddResponse, error)
	// Streams one response per matching item, newest inserted first. An empty result sends no messages.
	// Name filtering uses a substring match; number and timestamp bounds are inclusive.
	List(context.Context, *v1.ListRequest, NumberServiceListServerStream) error
	// Returns count, sum, average, minimum, maximum, and distinct-name count for the selected time range.
	// All aggregates are zero when no items match.
	Summary(context.Context, *v1.SummaryRequest) (*v1.SummaryResponse, error)
	// Returns counts, sums, and averages in ascending UTC time buckets. Empty buckets are omitted.
	// Weeks begin on Sunday; months begin on the first day.
	TimeSeries(context.Context, *v1.TimeSeriesRequest) (*v1.TimeSeriesResponse, error)
	// Groups values into approximately equal-width buckets over the observed range, including empty buckets.
	// No matching items produce no buckets; identical values produce a single bucket.
	Distribution(context.Context, *v1.DistributionRequest) (*v1.DistributionResponse, error)
	// Ranks names by item count, then total value, both descending, up to the requested limit.
	TopNames(context.Context, *v1.TopNamesRequest) (*v1.TopNamesResponse, error)
}

// RegisterNumberServiceHandler registers svc as the number.v1.NumberService implementation on
// server.
func RegisterNumberServiceHandler(server *connect.Server, svc NumberServiceHandler) {
	adapter := numberServiceHandler{svc: svc}
	server.Register(
		connect.Method{Spec: numberServiceAddSpec(), Handler: adapter.add},
		connect.Method{Spec: numberServiceListSpec(), Handler: adapter.list},
		connect.Method{Spec: numberServiceSummarySpec(), Handler: adapter.summary},
		connect.Method{Spec: numberServiceTimeSeriesSpec(), Handler: adapter.timeSeries},
		connect.Method{Spec: numberServiceDistributionSpec(), Handler: adapter.distribution},
		connect.Method{Spec: numberServiceTopNamesSpec(), Handler: adapter.topNames},
	)
}

// NumberServiceListServerStream is the server stream for the NumberService's List RPC.
type NumberServiceListServerStream struct {
	stream connect.ServerStream
}

// SendHeaders flushes the response headers without a message. The first Send does this implicitly.
func (s NumberServiceListServerStream) SendHeaders() error {
	return s.stream.SendHeaders()
}

// Send sends a response message to the client.
func (s NumberServiceListServerStream) Send(res *v1.ListResponse) error {
	return s.stream.Send(res)
}

// UnimplementedNumberServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedNumberServiceHandler struct{}

func (UnimplementedNumberServiceHandler) Add(context.Context, *v1.AddRequest) (*v1.AddResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "number.v1.NumberService.Add is not implemented")
}

func (UnimplementedNumberServiceHandler) List(context.Context, *v1.ListRequest, NumberServiceListServerStream) error {
	return connect.NewError(connect.CodeUnimplemented, "number.v1.NumberService.List is not implemented")
}

func (UnimplementedNumberServiceHandler) Summary(context.Context, *v1.SummaryRequest) (*v1.SummaryResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "number.v1.NumberService.Summary is not implemented")
}

func (UnimplementedNumberServiceHandler) TimeSeries(context.Context, *v1.TimeSeriesRequest) (*v1.TimeSeriesResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "number.v1.NumberService.TimeSeries is not implemented")
}

func (UnimplementedNumberServiceHandler) Distribution(context.Context, *v1.DistributionRequest) (*v1.DistributionResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "number.v1.NumberService.Distribution is not implemented")
}

func (UnimplementedNumberServiceHandler) TopNames(context.Context, *v1.TopNamesRequest) (*v1.TopNamesResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "number.v1.NumberService.TopNames is not implemented")
}

type numberServiceClient struct {
	client *connect.Client
}

func (c *numberServiceClient) Add(ctx context.Context, req *v1.AddRequest) (*v1.AddResponse, error) {
	var res v1.AddResponse
	if err := c.client.CallUnary(ctx, numberServiceAddSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *numberServiceClient) List(ctx context.Context, req *v1.ListRequest) (NumberServiceListClientStream, error) {
	stream, err := c.client.CallServerStream(ctx, numberServiceListSpec(), req)
	if err != nil {
		return NumberServiceListClientStream{}, err
	}
	return NumberServiceListClientStream{stream: stream}, nil
}

func (c *numberServiceClient) Summary(ctx context.Context, req *v1.SummaryRequest) (*v1.SummaryResponse, error) {
	var res v1.SummaryResponse
	if err := c.client.CallUnary(ctx, numberServiceSummarySpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *numberServiceClient) TimeSeries(ctx context.Context, req *v1.TimeSeriesRequest) (*v1.TimeSeriesResponse, error) {
	var res v1.TimeSeriesResponse
	if err := c.client.CallUnary(ctx, numberServiceTimeSeriesSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *numberServiceClient) Distribution(ctx context.Context, req *v1.DistributionRequest) (*v1.DistributionResponse, error) {
	var res v1.DistributionResponse
	if err := c.client.CallUnary(ctx, numberServiceDistributionSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *numberServiceClient) TopNames(ctx context.Context, req *v1.TopNamesRequest) (*v1.TopNamesResponse, error) {
	var res v1.TopNamesResponse
	if err := c.client.CallUnary(ctx, numberServiceTopNamesSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

type numberServiceHandler struct{ svc NumberServiceHandler }

func (h numberServiceHandler) add(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.AddRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.Add(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h numberServiceHandler) list(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.ListRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	return h.svc.List(ctx, &req, NumberServiceListServerStream{stream: stream})
}

func (h numberServiceHandler) summary(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.SummaryRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.Summary(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h numberServiceHandler) timeSeries(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.TimeSeriesRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.TimeSeries(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h numberServiceHandler) distribution(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.DistributionRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.Distribution(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h numberServiceHandler) topNames(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.TopNamesRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.TopNames(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}
