// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: number/v1/service.proto

package numberv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/spotdemo4/trevstack/server/connect/number/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// NumberServiceName is the fully-qualified name of the NumberService service.
	NumberServiceName = "number.v1.NumberService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// NumberServiceAddProcedure is the fully-qualified name of the NumberService's Add RPC.
	NumberServiceAddProcedure = "/number.v1.NumberService/Add"
	// NumberServiceListProcedure is the fully-qualified name of the NumberService's List RPC.
	NumberServiceListProcedure = "/number.v1.NumberService/List"
	// NumberServiceSummaryProcedure is the fully-qualified name of the NumberService's Summary RPC.
	NumberServiceSummaryProcedure = "/number.v1.NumberService/Summary"
	// NumberServiceTimeSeriesProcedure is the fully-qualified name of the NumberService's TimeSeries
	// RPC.
	NumberServiceTimeSeriesProcedure = "/number.v1.NumberService/TimeSeries"
	// NumberServiceDistributionProcedure is the fully-qualified name of the NumberService's
	// Distribution RPC.
	NumberServiceDistributionProcedure = "/number.v1.NumberService/Distribution"
	// NumberServiceTopNamesProcedure is the fully-qualified name of the NumberService's TopNames RPC.
	NumberServiceTopNamesProcedure = "/number.v1.NumberService/TopNames"
)

// NumberServiceClient is a client for the number.v1.NumberService service.
type NumberServiceClient interface {
	Add(context.Context, *v1.AddRequest) (*v1.AddResponse, error)
	List(context.Context, *v1.ListRequest) (*v1.ListResponse, error)
	Summary(context.Context, *v1.SummaryRequest) (*v1.SummaryResponse, error)
	TimeSeries(context.Context, *v1.TimeSeriesRequest) (*v1.TimeSeriesResponse, error)
	Distribution(context.Context, *v1.DistributionRequest) (*v1.DistributionResponse, error)
	TopNames(context.Context, *v1.TopNamesRequest) (*v1.TopNamesResponse, error)
}

// NewNumberServiceClient constructs a client for the number.v1.NumberService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewNumberServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) NumberServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	numberServiceMethods := v1.File_number_v1_service_proto.Services().ByName("NumberService").Methods()
	return &numberServiceClient{
		add: connect.NewClient[v1.AddRequest, v1.AddResponse](
			httpClient,
			baseURL+NumberServiceAddProcedure,
			connect.WithSchema(numberServiceMethods.ByName("Add")),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[v1.ListRequest, v1.ListResponse](
			httpClient,
			baseURL+NumberServiceListProcedure,
			connect.WithSchema(numberServiceMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		summary: connect.NewClient[v1.SummaryRequest, v1.SummaryResponse](
			httpClient,
			baseURL+NumberServiceSummaryProcedure,
			connect.WithSchema(numberServiceMethods.ByName("Summary")),
			connect.WithClientOptions(opts...),
		),
		timeSeries: connect.NewClient[v1.TimeSeriesRequest, v1.TimeSeriesResponse](
			httpClient,
			baseURL+NumberServiceTimeSeriesProcedure,
			connect.WithSchema(numberServiceMethods.ByName("TimeSeries")),
			connect.WithClientOptions(opts...),
		),
		distribution: connect.NewClient[v1.DistributionRequest, v1.DistributionResponse](
			httpClient,
			baseURL+NumberServiceDistributionProcedure,
			connect.WithSchema(numberServiceMethods.ByName("Distribution")),
			connect.WithClientOptions(opts...),
		),
		topNames: connect.NewClient[v1.TopNamesRequest, v1.TopNamesResponse](
			httpClient,
			baseURL+NumberServiceTopNamesProcedure,
			connect.WithSchema(numberServiceMethods.ByName("TopNames")),
			connect.WithClientOptions(opts...),
		),
	}
}

// numberServiceClient implements NumberServiceClient.
type numberServiceClient struct {
	add          *connect.Client[v1.AddRequest, v1.AddResponse]
	list         *connect.Client[v1.ListRequest, v1.ListResponse]
	summary      *connect.Client[v1.SummaryRequest, v1.SummaryResponse]
	timeSeries   *connect.Client[v1.TimeSeriesRequest, v1.TimeSeriesResponse]
	distribution *connect.Client[v1.DistributionRequest, v1.DistributionResponse]
	topNames     *connect.Client[v1.TopNamesRequest, v1.TopNamesResponse]
}

// Add calls number.v1.NumberService.Add.
func (c *numberServiceClient) Add(ctx context.Context, req *v1.AddRequest) (*v1.AddResponse, error) {
	response, err := c.add.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// List calls number.v1.NumberService.List.
func (c *numberServiceClient) List(ctx context.Context, req *v1.ListRequest) (*v1.ListResponse, error) {
	response, err := c.list.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// Summary calls number.v1.NumberService.Summary.
func (c *numberServiceClient) Summary(ctx context.Context, req *v1.SummaryRequest) (*v1.SummaryResponse, error) {
	response, err := c.summary.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// TimeSeries calls number.v1.NumberService.TimeSeries.
func (c *numberServiceClient) TimeSeries(ctx context.Context, req *v1.TimeSeriesRequest) (*v1.TimeSeriesResponse, error) {
	response, err := c.timeSeries.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// Distribution calls number.v1.NumberService.Distribution.
func (c *numberServiceClient) Distribution(ctx context.Context, req *v1.DistributionRequest) (*v1.DistributionResponse, error) {
	response, err := c.distribution.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// TopNames calls number.v1.NumberService.TopNames.
func (c *numberServiceClient) TopNames(ctx context.Context, req *v1.TopNamesRequest) (*v1.TopNamesResponse, error) {
	response, err := c.topNames.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// NumberServiceHandler is an implementation of the number.v1.NumberService service.
type NumberServiceHandler interface {
	Add(context.Context, *v1.AddRequest) (*v1.AddResponse, error)
	List(context.Context, *v1.ListRequest) (*v1.ListResponse, error)
	Summary(context.Context, *v1.SummaryRequest) (*v1.SummaryResponse, error)
	TimeSeries(context.Context, *v1.TimeSeriesRequest) (*v1.TimeSeriesResponse, error)
	Distribution(context.Context, *v1.DistributionRequest) (*v1.DistributionResponse, error)
	TopNames(context.Context, *v1.TopNamesRequest) (*v1.TopNamesResponse, error)
}

// NewNumberServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewNumberServiceHandler(svc NumberServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	numberServiceMethods := v1.File_number_v1_service_proto.Services().ByName("NumberService").Methods()
	numberServiceAddHandler := connect.NewUnaryHandlerSimple(
		NumberServiceAddProcedure,
		svc.Add,
		connect.WithSchema(numberServiceMethods.ByName("Add")),
		connect.WithHandlerOptions(opts...),
	)
	numberServiceListHandler := connect.NewUnaryHandlerSimple(
		NumberServiceListProcedure,
		svc.List,
		connect.WithSchema(numberServiceMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	numberServiceSummaryHandler := connect.NewUnaryHandlerSimple(
		NumberServiceSummaryProcedure,
		svc.Summary,
		connect.WithSchema(numberServiceMethods.ByName("Summary")),
		connect.WithHandlerOptions(opts...),
	)
	numberServiceTimeSeriesHandler := connect.NewUnaryHandlerSimple(
		NumberServiceTimeSeriesProcedure,
		svc.TimeSeries,
		connect.WithSchema(numberServiceMethods.ByName("TimeSeries")),
		connect.WithHandlerOptions(opts...),
	)
	numberServiceDistributionHandler := connect.NewUnaryHandlerSimple(
		NumberServiceDistributionProcedure,
		svc.Distribution,
		connect.WithSchema(numberServiceMethods.ByName("Distribution")),
		connect.WithHandlerOptions(opts...),
	)
	numberServiceTopNamesHandler := connect.NewUnaryHandlerSimple(
		NumberServiceTopNamesProcedure,
		svc.TopNames,
		connect.WithSchema(numberServiceMethods.ByName("TopNames")),
		connect.WithHandlerOptions(opts...),
	)
	return "/number.v1.NumberService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case NumberServiceAddProcedure:
			numberServiceAddHandler.ServeHTTP(w, r)
		case NumberServiceListProcedure:
			numberServiceListHandler.ServeHTTP(w, r)
		case NumberServiceSummaryProcedure:
			numberServiceSummaryHandler.ServeHTTP(w, r)
		case NumberServiceTimeSeriesProcedure:
			numberServiceTimeSeriesHandler.ServeHTTP(w, r)
		case NumberServiceDistributionProcedure:
			numberServiceDistributionHandler.ServeHTTP(w, r)
		case NumberServiceTopNamesProcedure:
			numberServiceTopNamesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedNumberServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedNumberServiceHandler struct{}

func (UnimplementedNumberServiceHandler) Add(context.Context, *v1.AddRequest) (*v1.AddResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("number.v1.NumberService.Add is not implemented"))
}

func (UnimplementedNumberServiceHandler) List(context.Context, *v1.ListRequest) (*v1.ListResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("number.v1.NumberService.List is not implemented"))
}

func (UnimplementedNumberServiceHandler) Summary(context.Context, *v1.SummaryRequest) (*v1.SummaryResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("number.v1.NumberService.Summary is not implemented"))
}

func (UnimplementedNumberServiceHandler) TimeSeries(context.Context, *v1.TimeSeriesRequest) (*v1.TimeSeriesResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("number.v1.NumberService.TimeSeries is not implemented"))
}

func (UnimplementedNumberServiceHandler) Distribution(context.Context, *v1.DistributionRequest) (*v1.DistributionResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("number.v1.NumberService.Distribution is not implemented"))
}

func (UnimplementedNumberServiceHandler) TopNames(context.Context, *v1.TopNamesRequest) (*v1.TopNamesResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("number.v1.NumberService.TopNames is not implemented"))
}
