// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: number/v1/list.proto

package numberv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Number        uint32                 `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_number_v1_list_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_number_v1_list_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_number_v1_list_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetNumber() uint32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        *int64                 `protobuf:"varint,1,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Min           *uint32                `protobuf:"varint,3,opt,name=min,proto3,oneof" json:"min,omitempty"`
	Max           *uint32                `protobuf:"varint,4,opt,name=max,proto3,oneof" json:"max,omitempty"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start,proto3,oneof" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end,proto3,oneof" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_number_v1_list_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_number_v1_list_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_number_v1_list_proto_rawDescGZIP(), []int{1}
}

func (x *ListRequest) GetCursor() int64 {
	if x != nil && x.Cursor != nil {
		return *x.Cursor
	}
	return 0
}

func (x *ListRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ListRequest) GetMin() uint32 {
	if x != nil && x.Min != nil {
		return *x.Min
	}
	return 0
}

func (x *ListRequest) GetMax() uint32 {
	if x != nil && x.Max != nil {
		return *x.Max
	}
	return 0
}

func (x *ListRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *ListRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	NextCursor    int64                  `protobuf:"varint,3,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_number_v1_list_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_number_v1_list_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_number_v1_list_proto_rawDescGZIP(), []int{2}
}

func (x *ListResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListResponse) GetNextCursor() int64 {
	if x != nil {
		return x.NextCursor
	}
	return 0
}

var File_number_v1_list_proto protoreflect.FileDescriptor

const file_number_v1_list_proto_rawDesc = "" +
	"\n" +
	"\x14number/v1/list.proto\x12\tnumber.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x84\x01\n" +
	"\x04Item\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1d\n" +
	"\x04name\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x182R\x04name\x12#\n" +
	"\x06number\x18\x03 \x01(\rB\v\xbaH\b*\x06\x18\xc0\x84=(\x00R\x06number\"\x8f\x04\n" +
	"\vListRequest\x12\x1b\n" +
	"\x06cursor\x18\x01 \x01(\x03H\x00R\x06cursor\x88\x01\x01\x12\"\n" +
	"\x04name\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x00\x182H\x01R\x04name\x88\x01\x01\x12\"\n" +
	"\x03min\x18\x03 \x01(\rB\v\xbaH\b*\x06\x18\xc0\x84=(\x00H\x02R\x03min\x88\x01\x01\x12\"\n" +
	"\x03max\x18\x04 \x01(\rB\v\xbaH\b*\x06\x18\xc0\x84=(\x00H\x03R\x03max\x88\x01\x01\x125\n" +
	"\x05start\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x04R\x05start\x88\x01\x01\x121\n" +
	"\x03end\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x05R\x03end\x88\x01\x01:\xd6\x01\xbaH\xd2\x01\x1ag\n" +
	"\x0fend_after_start\x12\x17End must be after start\x1a;!has(this.end) || !has(this.start) || this.end > this.start\x1ag\n" +
	"\x11min_less_than_max\x12\x19Min must be less than max\x1a7!has(this.min) || !has(this.max) || this.min < this.maxB\t\n" +
	"\a_cursorB\a\n" +
	"\x05_nameB\x06\n" +
	"\x04_minB\x06\n" +
	"\x04_maxB\b\n" +
	"\x06_startB\x06\n" +
	"\x04_end\"w\n" +
	"\fListResponse\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.number.v1.ItemR\x05items\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\x12\x1f\n" +
	"\vnext_cursor\x18\x03 \x01(\x03R\n" +
	"nextCursorB\xa1\x01\n" +
	"\rcom.number.v1B\tListProtoP\x01Z@github.com/spotdemo4/trevstack/server/connect/number/v1;numberv1\xa2\x02\x03NXX\xaa\x02\tNumber.V1\xca\x02\tNumber\\V1\xe2\x02\x15Number\\V1\\GPBMetadata\xea\x02\n" +
	"Number::V1b\x06proto3"

var (
	file_number_v1_list_proto_rawDescOnce sync.Once
	file_number_v1_list_proto_rawDescData []byte
)

func file_number_v1_list_proto_rawDescGZIP() []byte {
	file_number_v1_list_proto_rawDescOnce.Do(func() {
		file_number_v1_list_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_number_v1_list_proto_rawDesc), len(file_number_v1_list_proto_rawDesc)))
	})
	return file_number_v1_list_proto_rawDescData
}

var file_number_v1_list_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_number_v1_list_proto_goTypes = []any{
	(*Item)(nil),                  // 0: number.v1.Item
	(*ListRequest)(nil),           // 1: number.v1.ListRequest
	(*ListResponse)(nil),          // 2: number.v1.ListResponse
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_number_v1_list_proto_depIdxs = []int32{
	3, // 0: number.v1.Item.timestamp:type_name -> google.protobuf.Timestamp
	3, // 1: number.v1.ListRequest.start:type_name -> google.protobuf.Timestamp
	3, // 2: number.v1.ListRequest.end:type_name -> google.protobuf.Timestamp
	0, // 3: number.v1.ListResponse.items:type_name -> number.v1.Item
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_number_v1_list_proto_init() }
func file_number_v1_list_proto_init() {
	if File_number_v1_list_proto != nil {
		return
	}
	file_number_v1_list_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_number_v1_list_proto_rawDesc), len(file_number_v1_list_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_number_v1_list_proto_goTypes,
		DependencyIndexes: file_number_v1_list_proto_depIdxs,
		MessageInfos:      file_number_v1_list_proto_msgTypes,
	}.Build()
	File_number_v1_list_proto = out.File
	file_number_v1_list_proto_goTypes = nil
	file_number_v1_list_proto_depIdxs = nil
}
