// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: number/v1/metrics.proto

package numberv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Time-bucketed counts and sums, suitable for line/area charts.
type TimeInterval int32

const (
	TimeInterval_TIME_INTERVAL_UNSPECIFIED TimeInterval = 0
	TimeInterval_TIME_INTERVAL_HOUR        TimeInterval = 1
	TimeInterval_TIME_INTERVAL_DAY         TimeInterval = 2
	TimeInterval_TIME_INTERVAL_WEEK        TimeInterval = 3
	TimeInterval_TIME_INTERVAL_MONTH       TimeInterval = 4
)

// Enum value maps for TimeInterval.
var (
	TimeInterval_name = map[int32]string{
		0: "TIME_INTERVAL_UNSPECIFIED",
		1: "TIME_INTERVAL_HOUR",
		2: "TIME_INTERVAL_DAY",
		3: "TIME_INTERVAL_WEEK",
		4: "TIME_INTERVAL_MONTH",
	}
	TimeInterval_value = map[string]int32{
		"TIME_INTERVAL_UNSPECIFIED": 0,
		"TIME_INTERVAL_HOUR":        1,
		"TIME_INTERVAL_DAY":         2,
		"TIME_INTERVAL_WEEK":        3,
		"TIME_INTERVAL_MONTH":       4,
	}
)

func (x TimeInterval) Enum() *TimeInterval {
	p := new(TimeInterval)
	*p = x
	return p
}

func (x TimeInterval) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeInterval) Descriptor() protoreflect.EnumDescriptor {
	return file_number_v1_metrics_proto_enumTypes[0].Descriptor()
}

func (TimeInterval) Type() protoreflect.EnumType {
	return &file_number_v1_metrics_proto_enumTypes[0]
}

func (x TimeInterval) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimeInterval.Descriptor instead.
func (TimeInterval) EnumDescriptor() ([]byte, []int) {
	return file_number_v1_metrics_proto_rawDescGZIP(), []int{0}
}

// Scalar summary metrics across all items, suitable for stat cards.
type SummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start,proto3,oneof" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end,proto3,oneof" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummaryRequest) Reset() {
	*x = SummaryRequest{}
	mi := &file_number_v1_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryRequest) ProtoMessage() {}

func (x *SummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_number_v1_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryRequest.ProtoReflect.Descriptor instead.
func (*SummaryRequest) Descriptor() ([]byte, []int) {
	return file_number_v1_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *SummaryRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *SummaryRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

type SummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCount    int64                  `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	TotalSum      uint64                 `protobuf:"varint,2,opt,name=total_sum,json=totalSum,proto3" json:"total_sum,omitempty"`
	Average       float64                `protobuf:"fixed64,3,opt,name=average,proto3" json:"average,omitempty"`
	Min           uint32                 `protobuf:"varint,4,opt,name=min,proto3" json:"min,omitempty"`
	Max           uint32                 `protobuf:"varint,5,opt,name=max,proto3" json:"max,omitempty"`
	DistinctNames uint32                 `protobuf:"varint,6,opt,name=distinct_names,json=distinctNames,proto3" json:"distinct_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummaryResponse) Reset() {
	*x = SummaryResponse{}
	mi := &file_number_v1_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryResponse) ProtoMessage() {}

func (x *SummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_number_v1_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryResponse.ProtoReflect.Descriptor instead.
func (*SummaryResponse) Descriptor() ([]byte, []int) {
	return file_number_v1_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *SummaryResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *SummaryResponse) GetTotalSum() uint64 {
	if x != nil {
		return x.TotalSum
	}
	return 0
}

func (x *SummaryResponse) GetAverage() float64 {
	if x != nil {
		return x.Average
	}
	return 0
}

func (x *SummaryResponse) GetMin() uint32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *SummaryResponse) GetMax() uint32 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *SummaryResponse) GetDistinctNames() uint32 {
	if x != nil {
		return x.DistinctNames
	}
	return 0
}

type TimeSeriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interval      TimeInterval           `protobuf:"varint,1,opt,name=interval,proto3,enum=number.v1.TimeInterval" json:"interval,omitempty"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start,proto3,oneof" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end,proto3,oneof" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeSeriesRequest) Reset() {
	*x = TimeSeriesRequest{}
	mi := &file_number_v1_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSeriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSeriesRequest) ProtoMessage() {}

func (x *TimeSeriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_number_v1_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSeriesRequest.ProtoReflect.Descriptor instead.
func (*TimeSeriesRequest) Descriptor() ([]byte, []int) {
	return file_number_v1_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *TimeSeriesRequest) GetInterval() TimeInterval {
	if x != nil {
		return x.Interval
	}
	return TimeInterval_TIME_INTERVAL_UNSPECIFIED
}

func (x *TimeSeriesRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *TimeSeriesRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

type TimeSeriesPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Sum           uint64                 `protobuf:"varint,3,opt,name=sum,proto3" json:"sum,omitempty"`
	Average       float64                `protobuf:"fixed64,4,opt,name=average,proto3" json:"average,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeSeriesPoint) Reset() {
	*x = TimeSeriesPoint{}
	mi := &file_number_v1_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSeriesPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSeriesPoint) ProtoMessage() {}

func (x *TimeSeriesPoint) ProtoReflect() protoreflect.Message {
	mi := &file_number_v1_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSeriesPoint.ProtoReflect.Descriptor instead.
func (*TimeSeriesPoint) Descriptor() ([]byte, []int) {
	return file_number_v1_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *TimeSeriesPoint) GetBucket() *timestamppb.Timestamp {
	if x != nil {
		return x.Bucket
	}
	return nil
}

func (x *TimeSeriesPoint) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *TimeSeriesPoint) GetSum() uint64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *TimeSeriesPoint) GetAverage() float64 {
	if x != nil {
		return x.Average
	}
	return 0
}

type TimeSeriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*TimeSeriesPoint     `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeSeriesResponse) Reset() {
	*x = TimeSeriesResponse{}
	mi := &file_number_v1_metrics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSeriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSeriesResponse) ProtoMessage() {}

func (x *TimeSeriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_number_v1_metrics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSeriesResponse.ProtoReflect.Descriptor instead.
func (*TimeSeriesResponse) Descriptor() ([]byte, []int) {
	return file_number_v1_metrics_proto_rawDescGZIP(), []int{4}
}

func (x *TimeSeriesResponse) GetPoints() []*TimeSeriesPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

// Histogram of `number` values across equal-width buckets, suitable for bar charts.
type DistributionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketCount   uint32                 `protobuf:"varint,1,opt,name=bucket_count,json=bucketCount,proto3" json:"bucket_count,omitempty"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start,proto3,oneof" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end,proto3,oneof" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DistributionRequest) Reset() {
	*x = DistributionRequest{}
	mi := &file_number_v1_metrics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistributionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistributionRequest) ProtoMessage() {}

func (x *DistributionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_number_v1_metrics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistributionRequest.ProtoReflect.Descriptor instead.
func (*DistributionRequest) Descriptor() ([]byte, []int) {
	return file_number_v1_metrics_proto_rawDescGZIP(), []int{5}
}

func (x *DistributionRequest) GetBucketCount() uint32 {
	if x != nil {
		return x.BucketCount
	}
	return 0
}

func (x *DistributionRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *DistributionRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

type DistributionBucket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lower         uint32                 `protobuf:"varint,1,opt,name=lower,proto3" json:"lower,omitempty"`
	Upper         uint32                 `protobuf:"varint,2,opt,name=upper,proto3" json:"upper,omitempty"`
	Count         int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DistributionBucket) Reset() {
	*x = DistributionBucket{}
	mi := &file_number_v1_metrics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistributionBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistributionBucket) ProtoMessage() {}

func (x *DistributionBucket) ProtoReflect() protoreflect.Message {
	mi := &file_number_v1_metrics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistributionBucket.ProtoReflect.Descriptor instead.
func (*DistributionBucket) Descriptor() ([]byte, []int) {
	return file_number_v1_metrics_proto_rawDescGZIP(), []int{6}
}

func (x *DistributionBucket) GetLower() uint32 {
	if x != nil {
		return x.Lower
	}
	return 0
}

func (x *DistributionBucket) GetUpper() uint32 {
	if x != nil {
		return x.Upper
	}
	return 0
}

func (x *DistributionBucket) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type DistributionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buckets       []*DistributionBucket  `protobuf:"bytes,1,rep,name=buckets,proto3" json:"buckets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DistributionResponse) Reset() {
	*x = DistributionResponse{}
	mi := &file_number_v1_metrics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistributionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistributionResponse) ProtoMessage() {}

func (x *DistributionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_number_v1_metrics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistributionResponse.ProtoReflect.Descriptor instead.
func (*DistributionResponse) Descriptor() ([]byte, []int) {
	return file_number_v1_metrics_proto_rawDescGZIP(), []int{7}
}

func (x *DistributionResponse) GetBuckets() []*DistributionBucket {
	if x != nil {
		return x.Buckets
	}
	return nil
}

// Top N names by frequency and total value, suitable for bar/pie charts.
type TopNamesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint32                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start,proto3,oneof" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end,proto3,oneof" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopNamesRequest) Reset() {
	*x = TopNamesRequest{}
	mi := &file_number_v1_metrics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopNamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopNamesRequest) ProtoMessage() {}

func (x *TopNamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_number_v1_metrics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopNamesRequest.ProtoReflect.Descriptor instead.
func (*TopNamesRequest) Descriptor() ([]byte, []int) {
	return file_number_v1_metrics_proto_rawDescGZIP(), []int{8}
}

func (x *TopNamesRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *TopNamesRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *TopNamesRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

type TopName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Sum           uint64                 `protobuf:"varint,3,opt,name=sum,proto3" json:"sum,omitempty"`
	Average       float64                `protobuf:"fixed64,4,opt,name=average,proto3" json:"average,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopName) Reset() {
	*x = TopName{}
	mi := &file_number_v1_metrics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopName) ProtoMessage() {}

func (x *TopName) ProtoReflect() protoreflect.Message {
	mi := &file_number_v1_metrics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopName.ProtoReflect.Descriptor instead.
func (*TopName) Descriptor() ([]byte, []int) {
	return file_number_v1_metrics_proto_rawDescGZIP(), []int{9}
}

func (x *TopName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TopName) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *TopName) GetSum() uint64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *TopName) GetAverage() float64 {
	if x != nil {
		return x.Average
	}
	return 0
}

type TopNamesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []*TopName             `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopNamesResponse) Reset() {
	*x = TopNamesResponse{}
	mi := &file_number_v1_metrics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopNamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopNamesResponse) ProtoMessage() {}

func (x *TopNamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_number_v1_metrics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopNamesResponse.ProtoReflect.Descriptor instead.
func (*TopNamesResponse) Descriptor() ([]byte, []int) {
	return file_number_v1_metrics_proto_rawDescGZIP(), []int{10}
}

func (x *TopNamesResponse) GetNames() []*TopName {
	if x != nil {
		return x.Names
	}
	return nil
}

var File_number_v1_metrics_proto protoreflect.FileDescriptor

const file_number_v1_metrics_proto_rawDesc = "" +
	"\n" +
	"\x17number/v1/metrics.proto\x12\tnumber.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfa\x01\n" +
	"\x0eSummaryRequest\x125\n" +
	"\x05start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x05start\x88\x01\x01\x121\n" +
	"\x03end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x03end\x88\x01\x01:l\xbaHi\x1ag\n" +
	"\x0fend_after_start\x12\x17End must be after start\x1a;!has(this.end) || !has(this.start) || this.end > this.startB\b\n" +
	"\x06_startB\x06\n" +
	"\x04_end\"\xb4\x01\n" +
	"\x0fSummaryResponse\x12\x1f\n" +
	"\vtotal_count\x18\x01 \x01(\x03R\n" +
	"totalCount\x12\x1b\n" +
	"\ttotal_sum\x18\x02 \x01(\x04R\btotalSum\x12\x18\n" +
	"\aaverage\x18\x03 \x01(\x01R\aaverage\x12\x10\n" +
	"\x03min\x18\x04 \x01(\rR\x03min\x12\x10\n" +
	"\x03max\x18\x05 \x01(\rR\x03max\x12%\n" +
	"\x0edistinct_names\x18\x06 \x01(\rR\rdistinctNames\"\xbe\x02\n" +
	"\x11TimeSeriesRequest\x12?\n" +
	"\binterval\x18\x01 \x01(\x0e2\x17.number.v1.TimeIntervalB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\binterval\x125\n" +
	"\x05start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x05start\x88\x01\x01\x121\n" +
	"\x03end\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x03end\x88\x01\x01:l\xbaHi\x1ag\n" +
	"\x0fend_after_start\x12\x17End must be after start\x1a;!has(this.end) || !has(this.start) || this.end > this.startB\b\n" +
	"\x06_startB\x06\n" +
	"\x04_end\"\x87\x01\n" +
	"\x0fTimeSeriesPoint\x122\n" +
	"\x06bucket\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x06bucket\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12\x10\n" +
	"\x03sum\x18\x03 \x01(\x04R\x03sum\x12\x18\n" +
	"\aaverage\x18\x04 \x01(\x01R\aaverage\"H\n" +
	"\x12TimeSeriesResponse\x122\n" +
	"\x06points\x18\x01 \x03(\v2\x1a.number.v1.TimeSeriesPointR\x06points\"\xad\x02\n" +
	"\x13DistributionRequest\x12,\n" +
	"\fbucket_count\x18\x01 \x01(\rB\t\xbaH\x06*\x04\x18d(\x01R\vbucketCount\x125\n" +
	"\x05start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x05start\x88\x01\x01\x121\n" +
	"\x03end\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x03end\x88\x01\x01:l\xbaHi\x1ag\n" +
	"\x0fend_after_start\x12\x17End must be after start\x1a;!has(this.end) || !has(this.start) || this.end > this.startB\b\n" +
	"\x06_startB\x06\n" +
	"\x04_end\"V\n" +
	"\x12DistributionBucket\x12\x14\n" +
	"\x05lower\x18\x01 \x01(\rR\x05lower\x12\x14\n" +
	"\x05upper\x18\x02 \x01(\rR\x05upper\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\"O\n" +
	"\x14DistributionResponse\x127\n" +
	"\abuckets\x18\x01 \x03(\v2\x1d.number.v1.DistributionBucketR\abuckets\"\x9c\x02\n" +
	"\x0fTopNamesRequest\x12\x1f\n" +
	"\x05limit\x18\x01 \x01(\rB\t\xbaH\x06*\x04\x18d(\x01R\x05limit\x125\n" +
	"\x05start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x05start\x88\x01\x01\x121\n" +
	"\x03end\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x03end\x88\x01\x01:l\xbaHi\x1ag\n" +
	"\x0fend_after_start\x12\x17End must be after start\x1a;!has(this.end) || !has(this.start) || this.end > this.startB\b\n" +
	"\x06_startB\x06\n" +
	"\x04_end\"_\n" +
	"\aTopName\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12\x10\n" +
	"\x03sum\x18\x03 \x01(\x04R\x03sum\x12\x18\n" +
	"\aaverage\x18\x04 \x01(\x01R\aaverage\"<\n" +
	"\x10TopNamesResponse\x12(\n" +
	"\x05names\x18\x01 \x03(\v2\x12.number.v1.TopNameR\x05names*\x8d\x01\n" +
	"\fTimeInterval\x12\x1d\n" +
	"\x19TIME_INTERVAL_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TIME_INTERVAL_HOUR\x10\x01\x12\x15\n" +
	"\x11TIME_INTERVAL_DAY\x10\x02\x12\x16\n" +
	"\x12TIME_INTERVAL_WEEK\x10\x03\x12\x17\n" +
	"\x13TIME_INTERVAL_MONTH\x10\x04B\xa4\x01\n" +
	"\rcom.number.v1B\fMetricsProtoP\x01Z@github.com/spotdemo4/trevstack/server/connect/number/v1;numberv1\xa2\x02\x03NXX\xaa\x02\tNumber.V1\xca\x02\tNumber\\V1\xe2\x02\x15Number\\V1\\GPBMetadata\xea\x02\n" +
	"Number::V1b\x06proto3"

var (
	file_number_v1_metrics_proto_rawDescOnce sync.Once
	file_number_v1_metrics_proto_rawDescData []byte
)

func file_number_v1_metrics_proto_rawDescGZIP() []byte {
	file_number_v1_metrics_proto_rawDescOnce.Do(func() {
		file_number_v1_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_number_v1_metrics_proto_rawDesc), len(file_number_v1_metrics_proto_rawDesc)))
	})
	return file_number_v1_metrics_proto_rawDescData
}

var file_number_v1_metrics_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_number_v1_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_number_v1_metrics_proto_goTypes = []any{
	(TimeInterval)(0),             // 0: number.v1.TimeInterval
	(*SummaryRequest)(nil),        // 1: number.v1.SummaryRequest
	(*SummaryResponse)(nil),       // 2: number.v1.SummaryResponse
	(*TimeSeriesRequest)(nil),     // 3: number.v1.TimeSeriesRequest
	(*TimeSeriesPoint)(nil),       // 4: number.v1.TimeSeriesPoint
	(*TimeSeriesResponse)(nil),    // 5: number.v1.TimeSeriesResponse
	(*DistributionRequest)(nil),   // 6: number.v1.DistributionRequest
	(*DistributionBucket)(nil),    // 7: number.v1.DistributionBucket
	(*DistributionResponse)(nil),  // 8: number.v1.DistributionResponse
	(*TopNamesRequest)(nil),       // 9: number.v1.TopNamesRequest
	(*TopName)(nil),               // 10: number.v1.TopName
	(*TopNamesResponse)(nil),      // 11: number.v1.TopNamesResponse
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_number_v1_metrics_proto_depIdxs = []int32{
	12, // 0: number.v1.SummaryRequest.start:type_name -> google.protobuf.Timestamp
	12, // 1: number.v1.SummaryRequest.end:type_name -> google.protobuf.Timestamp
	0,  // 2: number.v1.TimeSeriesRequest.interval:type_name -> number.v1.TimeInterval
	12, // 3: number.v1.TimeSeriesRequest.start:type_name -> google.protobuf.Timestamp
	12, // 4: number.v1.TimeSeriesRequest.end:type_name -> google.protobuf.Timestamp
	12, // 5: number.v1.TimeSeriesPoint.bucket:type_name -> google.protobuf.Timestamp
	4,  // 6: number.v1.TimeSeriesResponse.points:type_name -> number.v1.TimeSeriesPoint
	12, // 7: number.v1.DistributionRequest.start:type_name -> google.protobuf.Timestamp
	12, // 8: number.v1.DistributionRequest.end:type_name -> google.protobuf.Timestamp
	7,  // 9: number.v1.DistributionResponse.buckets:type_name -> number.v1.DistributionBucket
	12, // 10: number.v1.TopNamesRequest.start:type_name -> google.protobuf.Timestamp
	12, // 11: number.v1.TopNamesRequest.end:type_name -> google.protobuf.Timestamp
	10, // 12: number.v1.TopNamesResponse.names:type_name -> number.v1.TopName
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_number_v1_metrics_proto_init() }
func file_number_v1_metrics_proto_init() {
	if File_number_v1_metrics_proto != nil {
		return
	}
	file_number_v1_metrics_proto_msgTypes[0].OneofWrappers = []any{}
	file_number_v1_metrics_proto_msgTypes[2].OneofWrappers = []any{}
	file_number_v1_metrics_proto_msgTypes[5].OneofWrappers = []any{}
	file_number_v1_metrics_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_number_v1_metrics_proto_rawDesc), len(file_number_v1_metrics_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_number_v1_metrics_proto_goTypes,
		DependencyIndexes: file_number_v1_metrics_proto_depIdxs,
		EnumInfos:         file_number_v1_metrics_proto_enumTypes,
		MessageInfos:      file_number_v1_metrics_proto_msgTypes,
	}.Build()
	File_number_v1_metrics_proto = out.File
	file_number_v1_metrics_proto_goTypes = nil
	file_number_v1_metrics_proto_depIdxs = nil
}
