// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: number/v1/metrics.proto

package numberv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Time-bucketed counts and sums, suitable for line/area charts.
type TimeInterval int32

const (
	TimeInterval_TIME_INTERVAL_UNSPECIFIED TimeInterval = 0
	TimeInterval_TIME_INTERVAL_HOUR        TimeInterval = 1
	TimeInterval_TIME_INTERVAL_DAY         TimeInterval = 2
	TimeInterval_TIME_INTERVAL_WEEK        TimeInterval = 3
	TimeInterval_TIME_INTERVAL_MONTH       TimeInterval = 4
)

// Enum value maps for TimeInterval.
var (
	TimeInterval_name = map[int32]string{
		0: "TIME_INTERVAL_UNSPECIFIED",
		1: "TIME_INTERVAL_HOUR",
		2: "TIME_INTERVAL_DAY",
		3: "TIME_INTERVAL_WEEK",
		4: "TIME_INTERVAL_MONTH",
	}
	TimeInterval_value = map[string]int32{
		"TIME_INTERVAL_UNSPECIFIED": 0,
		"TIME_INTERVAL_HOUR":        1,
		"TIME_INTERVAL_DAY":         2,
		"TIME_INTERVAL_WEEK":        3,
		"TIME_INTERVAL_MONTH":       4,
	}
)

func (x TimeInterval) Enum() *TimeInterval {
	p := new(TimeInterval)
	*p = x
	return p
}

func (x TimeInterval) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeInterval) Descriptor() protoreflect.EnumDescriptor {
	return file_number_v1_metrics_proto_enumTypes[0].Descriptor()
}

func (TimeInterval) Type() protoreflect.EnumType {
	return &file_number_v1_metrics_proto_enumTypes[0]
}

func (x TimeInterval) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Scalar summary metrics across all items, suitable for stat cards.
type SummaryRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Start *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start"`
	xxx_hidden_End   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SummaryRequest) Reset() {
	*x = SummaryRequest{}
	mi := &file_number_v1_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryRequest) ProtoMessage() {}

func (x *SummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_number_v1_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SummaryRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Start
	}
	return nil
}

func (x *SummaryRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_End
	}
	return nil
}

func (x *SummaryRequest) SetStart(v *timestamppb.Timestamp) {
	x.xxx_hidden_Start = v
}

func (x *SummaryRequest) SetEnd(v *timestamppb.Timestamp) {
	x.xxx_hidden_End = v
}

func (x *SummaryRequest) HasStart() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Start != nil
}

func (x *SummaryRequest) HasEnd() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_End != nil
}

func (x *SummaryRequest) ClearStart() {
	x.xxx_hidden_Start = nil
}

func (x *SummaryRequest) ClearEnd() {
	x.xxx_hidden_End = nil
}

type SummaryRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Start *timestamppb.Timestamp
	End   *timestamppb.Timestamp
}

func (b0 SummaryRequest_builder) Build() *SummaryRequest {
	m0 := &SummaryRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Start = b.Start
	x.xxx_hidden_End = b.End
	return m0
}

type SummaryResponse struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TotalCount    int64                  `protobuf:"varint,1,opt,name=total_count,json=totalCount"`
	xxx_hidden_TotalSum      uint64                 `protobuf:"varint,2,opt,name=total_sum,json=totalSum"`
	xxx_hidden_Average       float64                `protobuf:"fixed64,3,opt,name=average"`
	xxx_hidden_Min           uint32                 `protobuf:"varint,4,opt,name=min"`
	xxx_hidden_Max           uint32                 `protobuf:"varint,5,opt,name=max"`
	xxx_hidden_DistinctNames uint32                 `protobuf:"varint,6,opt,name=distinct_names,json=distinctNames"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *SummaryResponse) Reset() {
	*x = SummaryResponse{}
	mi := &file_number_v1_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryResponse) ProtoMessage() {}

func (x *SummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_number_v1_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SummaryResponse) GetTotalCount() int64 {
	if x != nil {
		return x.xxx_hidden_TotalCount
	}
	return 0
}

func (x *SummaryResponse) GetTotalSum() uint64 {
	if x != nil {
		return x.xxx_hidden_TotalSum
	}
	return 0
}

func (x *SummaryResponse) GetAverage() float64 {
	if x != nil {
		return x.xxx_hidden_Average
	}
	return 0
}

func (x *SummaryResponse) GetMin() uint32 {
	if x != nil {
		return x.xxx_hidden_Min
	}
	return 0
}

func (x *SummaryResponse) GetMax() uint32 {
	if x != nil {
		return x.xxx_hidden_Max
	}
	return 0
}

func (x *SummaryResponse) GetDistinctNames() uint32 {
	if x != nil {
		return x.xxx_hidden_DistinctNames
	}
	return 0
}

func (x *SummaryResponse) SetTotalCount(v int64) {
	x.xxx_hidden_TotalCount = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *SummaryResponse) SetTotalSum(v uint64) {
	x.xxx_hidden_TotalSum = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *SummaryResponse) SetAverage(v float64) {
	x.xxx_hidden_Average = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *SummaryResponse) SetMin(v uint32) {
	x.xxx_hidden_Min = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *SummaryResponse) SetMax(v uint32) {
	x.xxx_hidden_Max = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *SummaryResponse) SetDistinctNames(v uint32) {
	x.xxx_hidden_DistinctNames = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *SummaryResponse) HasTotalCount() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SummaryResponse) HasTotalSum() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *SummaryResponse) HasAverage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *SummaryResponse) HasMin() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *SummaryResponse) HasMax() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *SummaryResponse) HasDistinctNames() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *SummaryResponse) ClearTotalCount() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_TotalCount = 0
}

func (x *SummaryResponse) ClearTotalSum() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_TotalSum = 0
}

func (x *SummaryResponse) ClearAverage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Average = 0
}

func (x *SummaryResponse) ClearMin() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Min = 0
}

func (x *SummaryResponse) ClearMax() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Max = 0
}

func (x *SummaryResponse) ClearDistinctNames() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_DistinctNames = 0
}

type SummaryResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TotalCount    *int64
	TotalSum      *uint64
	Average       *float64
	Min           *uint32
	Max           *uint32
	DistinctNames *uint32
}

func (b0 SummaryResponse_builder) Build() *SummaryResponse {
	m0 := &SummaryResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.TotalCount != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_TotalCount = *b.TotalCount
	}
	if b.TotalSum != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_TotalSum = *b.TotalSum
	}
	if b.Average != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_Average = *b.Average
	}
	if b.Min != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_Min = *b.Min
	}
	if b.Max != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_Max = *b.Max
	}
	if b.DistinctNames != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_DistinctNames = *b.DistinctNames
	}
	return m0
}

type TimeSeriesRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Interval    TimeInterval           `protobuf:"varint,1,opt,name=interval,enum=number.v1.TimeInterval"`
	xxx_hidden_Start       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start"`
	xxx_hidden_End         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TimeSeriesRequest) Reset() {
	*x = TimeSeriesRequest{}
	mi := &file_number_v1_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSeriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSeriesRequest) ProtoMessage() {}

func (x *TimeSeriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_number_v1_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TimeSeriesRequest) GetInterval() TimeInterval {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Interval
		}
	}
	return TimeInterval_TIME_INTERVAL_UNSPECIFIED
}

func (x *TimeSeriesRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Start
	}
	return nil
}

func (x *TimeSeriesRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_End
	}
	return nil
}

func (x *TimeSeriesRequest) SetInterval(v TimeInterval) {
	x.xxx_hidden_Interval = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *TimeSeriesRequest) SetStart(v *timestamppb.Timestamp) {
	x.xxx_hidden_Start = v
}

func (x *TimeSeriesRequest) SetEnd(v *timestamppb.Timestamp) {
	x.xxx_hidden_End = v
}

func (x *TimeSeriesRequest) HasInterval() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *TimeSeriesRequest) HasStart() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Start != nil
}

func (x *TimeSeriesRequest) HasEnd() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_End != nil
}

func (x *TimeSeriesRequest) ClearInterval() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Interval = TimeInterval_TIME_INTERVAL_UNSPECIFIED
}

func (x *TimeSeriesRequest) ClearStart() {
	x.xxx_hidden_Start = nil
}

func (x *TimeSeriesRequest) ClearEnd() {
	x.xxx_hidden_End = nil
}

type TimeSeriesRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Interval *TimeInterval
	Start    *timestamppb.Timestamp
	End      *timestamppb.Timestamp
}

func (b0 TimeSeriesRequest_builder) Build() *TimeSeriesRequest {
	m0 := &TimeSeriesRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Interval != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Interval = *b.Interval
	}
	x.xxx_hidden_Start = b.Start
	x.xxx_hidden_End = b.End
	return m0
}

type TimeSeriesPoint struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Bucket      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=bucket"`
	xxx_hidden_Count       int64                  `protobuf:"varint,2,opt,name=count"`
	xxx_hidden_Sum         uint64                 `protobuf:"varint,3,opt,name=sum"`
	xxx_hidden_Average     float64                `protobuf:"fixed64,4,opt,name=average"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TimeSeriesPoint) Reset() {
	*x = TimeSeriesPoint{}
	mi := &file_number_v1_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSeriesPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSeriesPoint) ProtoMessage() {}

func (x *TimeSeriesPoint) ProtoReflect() protoreflect.Message {
	mi := &file_number_v1_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TimeSeriesPoint) GetBucket() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Bucket
	}
	return nil
}

func (x *TimeSeriesPoint) GetCount() int64 {
	if x != nil {
		return x.xxx_hidden_Count
	}
	return 0
}

func (x *TimeSeriesPoint) GetSum() uint64 {
	if x != nil {
		return x.xxx_hidden_Sum
	}
	return 0
}

func (x *TimeSeriesPoint) GetAverage() float64 {
	if x != nil {
		return x.xxx_hidden_Average
	}
	return 0
}

func (x *TimeSeriesPoint) SetBucket(v *timestamppb.Timestamp) {
	x.xxx_hidden_Bucket = v
}

func (x *TimeSeriesPoint) SetCount(v int64) {
	x.xxx_hidden_Count = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *TimeSeriesPoint) SetSum(v uint64) {
	x.xxx_hidden_Sum = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *TimeSeriesPoint) SetAverage(v float64) {
	x.xxx_hidden_Average = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *TimeSeriesPoint) HasBucket() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Bucket != nil
}

func (x *TimeSeriesPoint) HasCount() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *TimeSeriesPoint) HasSum() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *TimeSeriesPoint) HasAverage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *TimeSeriesPoint) ClearBucket() {
	x.xxx_hidden_Bucket = nil
}

func (x *TimeSeriesPoint) ClearCount() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Count = 0
}

func (x *TimeSeriesPoint) ClearSum() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Sum = 0
}

func (x *TimeSeriesPoint) ClearAverage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Average = 0
}

type TimeSeriesPoint_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Bucket  *timestamppb.Timestamp
	Count   *int64
	Sum     *uint64
	Average *float64
}

func (b0 TimeSeriesPoint_builder) Build() *TimeSeriesPoint {
	m0 := &TimeSeriesPoint{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Bucket = b.Bucket
	if b.Count != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Count = *b.Count
	}
	if b.Sum != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Sum = *b.Sum
	}
	if b.Average != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Average = *b.Average
	}
	return m0
}

type TimeSeriesResponse struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Points *[]*TimeSeriesPoint    `protobuf:"bytes,1,rep,name=points"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TimeSeriesResponse) Reset() {
	*x = TimeSeriesResponse{}
	mi := &file_number_v1_metrics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSeriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSeriesResponse) ProtoMessage() {}

func (x *TimeSeriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_number_v1_metrics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TimeSeriesResponse) GetPoints() []*TimeSeriesPoint {
	if x != nil {
		if x.xxx_hidden_Points != nil {
			return *x.xxx_hidden_Points
		}
	}
	return nil
}

func (x *TimeSeriesResponse) SetPoints(v []*TimeSeriesPoint) {
	x.xxx_hidden_Points = &v
}

type TimeSeriesResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Points []*TimeSeriesPoint
}

func (b0 TimeSeriesResponse_builder) Build() *TimeSeriesResponse {
	m0 := &TimeSeriesResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Points = &b.Points
	return m0
}

// Histogram of `number` values across equal-width buckets, suitable for bar charts.
type DistributionRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_BucketCount uint32                 `protobuf:"varint,1,opt,name=bucket_count,json=bucketCount"`
	xxx_hidden_Start       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start"`
	xxx_hidden_End         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DistributionRequest) Reset() {
	*x = DistributionRequest{}
	mi := &file_number_v1_metrics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistributionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistributionRequest) ProtoMessage() {}

func (x *DistributionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_number_v1_metrics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DistributionRequest) GetBucketCount() uint32 {
	if x != nil {
		return x.xxx_hidden_BucketCount
	}
	return 0
}

func (x *DistributionRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Start
	}
	return nil
}

func (x *DistributionRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_End
	}
	return nil
}

func (x *DistributionRequest) SetBucketCount(v uint32) {
	x.xxx_hidden_BucketCount = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *DistributionRequest) SetStart(v *timestamppb.Timestamp) {
	x.xxx_hidden_Start = v
}

func (x *DistributionRequest) SetEnd(v *timestamppb.Timestamp) {
	x.xxx_hidden_End = v
}

func (x *DistributionRequest) HasBucketCount() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DistributionRequest) HasStart() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Start != nil
}

func (x *DistributionRequest) HasEnd() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_End != nil
}

func (x *DistributionRequest) ClearBucketCount() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_BucketCount = 0
}

func (x *DistributionRequest) ClearStart() {
	x.xxx_hidden_Start = nil
}

func (x *DistributionRequest) ClearEnd() {
	x.xxx_hidden_End = nil
}

type DistributionRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	BucketCount *uint32
	Start       *timestamppb.Timestamp
	End         *timestamppb.Timestamp
}

func (b0 DistributionRequest_builder) Build() *DistributionRequest {
	m0 := &DistributionRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.BucketCount != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_BucketCount = *b.BucketCount
	}
	x.xxx_hidden_Start = b.Start
	x.xxx_hidden_End = b.End
	return m0
}

type DistributionBucket struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Lower       uint32                 `protobuf:"varint,1,opt,name=lower"`
	xxx_hidden_Upper       uint32                 `protobuf:"varint,2,opt,name=upper"`
	xxx_hidden_Count       int64                  `protobuf:"varint,3,opt,name=count"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DistributionBucket) Reset() {
	*x = DistributionBucket{}
	mi := &file_number_v1_metrics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistributionBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistributionBucket) ProtoMessage() {}

func (x *DistributionBucket) ProtoReflect() protoreflect.Message {
	mi := &file_number_v1_metrics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DistributionBucket) GetLower() uint32 {
	if x != nil {
		return x.xxx_hidden_Lower
	}
	return 0
}

func (x *DistributionBucket) GetUpper() uint32 {
	if x != nil {
		return x.xxx_hidden_Upper
	}
	return 0
}

func (x *DistributionBucket) GetCount() int64 {
	if x != nil {
		return x.xxx_hidden_Count
	}
	return 0
}

func (x *DistributionBucket) SetLower(v uint32) {
	x.xxx_hidden_Lower = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *DistributionBucket) SetUpper(v uint32) {
	x.xxx_hidden_Upper = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *DistributionBucket) SetCount(v int64) {
	x.xxx_hidden_Count = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *DistributionBucket) HasLower() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DistributionBucket) HasUpper() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DistributionBucket) HasCount() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *DistributionBucket) ClearLower() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Lower = 0
}

func (x *DistributionBucket) ClearUpper() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Upper = 0
}

func (x *DistributionBucket) ClearCount() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Count = 0
}

type DistributionBucket_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Lower *uint32
	Upper *uint32
	Count *int64
}

func (b0 DistributionBucket_builder) Build() *DistributionBucket {
	m0 := &DistributionBucket{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Lower != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Lower = *b.Lower
	}
	if b.Upper != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Upper = *b.Upper
	}
	if b.Count != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Count = *b.Count
	}
	return m0
}

type DistributionResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Buckets *[]*DistributionBucket `protobuf:"bytes,1,rep,name=buckets"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DistributionResponse) Reset() {
	*x = DistributionResponse{}
	mi := &file_number_v1_metrics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistributionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistributionResponse) ProtoMessage() {}

func (x *DistributionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_number_v1_metrics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DistributionResponse) GetBuckets() []*DistributionBucket {
	if x != nil {
		if x.xxx_hidden_Buckets != nil {
			return *x.xxx_hidden_Buckets
		}
	}
	return nil
}

func (x *DistributionResponse) SetBuckets(v []*DistributionBucket) {
	x.xxx_hidden_Buckets = &v
}

type DistributionResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Buckets []*DistributionBucket
}

func (b0 DistributionResponse_builder) Build() *DistributionResponse {
	m0 := &DistributionResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Buckets = &b.Buckets
	return m0
}

// Top N names by frequency and total value, suitable for bar/pie charts.
type TopNamesRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Limit       uint32                 `protobuf:"varint,1,opt,name=limit"`
	xxx_hidden_Start       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start"`
	xxx_hidden_End         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TopNamesRequest) Reset() {
	*x = TopNamesRequest{}
	mi := &file_number_v1_metrics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopNamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopNamesRequest) ProtoMessage() {}

func (x *TopNamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_number_v1_metrics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TopNamesRequest) GetLimit() uint32 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *TopNamesRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Start
	}
	return nil
}

func (x *TopNamesRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_End
	}
	return nil
}

func (x *TopNamesRequest) SetLimit(v uint32) {
	x.xxx_hidden_Limit = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *TopNamesRequest) SetStart(v *timestamppb.Timestamp) {
	x.xxx_hidden_Start = v
}

func (x *TopNamesRequest) SetEnd(v *timestamppb.Timestamp) {
	x.xxx_hidden_End = v
}

func (x *TopNamesRequest) HasLimit() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *TopNamesRequest) HasStart() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Start != nil
}

func (x *TopNamesRequest) HasEnd() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_End != nil
}

func (x *TopNamesRequest) ClearLimit() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Limit = 0
}

func (x *TopNamesRequest) ClearStart() {
	x.xxx_hidden_Start = nil
}

func (x *TopNamesRequest) ClearEnd() {
	x.xxx_hidden_End = nil
}

type TopNamesRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Limit *uint32
	Start *timestamppb.Timestamp
	End   *timestamppb.Timestamp
}

func (b0 TopNamesRequest_builder) Build() *TopNamesRequest {
	m0 := &TopNamesRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Limit != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Limit = *b.Limit
	}
	x.xxx_hidden_Start = b.Start
	x.xxx_hidden_End = b.End
	return m0
}

type TopName struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Count       int64                  `protobuf:"varint,2,opt,name=count"`
	xxx_hidden_Sum         uint64                 `protobuf:"varint,3,opt,name=sum"`
	xxx_hidden_Average     float64                `protobuf:"fixed64,4,opt,name=average"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TopName) Reset() {
	*x = TopName{}
	mi := &file_number_v1_metrics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopName) ProtoMessage() {}

func (x *TopName) ProtoReflect() protoreflect.Message {
	mi := &file_number_v1_metrics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TopName) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *TopName) GetCount() int64 {
	if x != nil {
		return x.xxx_hidden_Count
	}
	return 0
}

func (x *TopName) GetSum() uint64 {
	if x != nil {
		return x.xxx_hidden_Sum
	}
	return 0
}

func (x *TopName) GetAverage() float64 {
	if x != nil {
		return x.xxx_hidden_Average
	}
	return 0
}

func (x *TopName) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *TopName) SetCount(v int64) {
	x.xxx_hidden_Count = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *TopName) SetSum(v uint64) {
	x.xxx_hidden_Sum = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *TopName) SetAverage(v float64) {
	x.xxx_hidden_Average = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *TopName) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *TopName) HasCount() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *TopName) HasSum() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *TopName) HasAverage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *TopName) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *TopName) ClearCount() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Count = 0
}

func (x *TopName) ClearSum() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Sum = 0
}

func (x *TopName) ClearAverage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Average = 0
}

type TopName_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name    *string
	Count   *int64
	Sum     *uint64
	Average *float64
}

func (b0 TopName_builder) Build() *TopName {
	m0 := &TopName{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Name = b.Name
	}
	if b.Count != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Count = *b.Count
	}
	if b.Sum != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Sum = *b.Sum
	}
	if b.Average != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Average = *b.Average
	}
	return m0
}

type TopNamesResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Names *[]*TopName            `protobuf:"bytes,1,rep,name=names"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TopNamesResponse) Reset() {
	*x = TopNamesResponse{}
	mi := &file_number_v1_metrics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopNamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopNamesResponse) ProtoMessage() {}

func (x *TopNamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_number_v1_metrics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TopNamesResponse) GetNames() []*TopName {
	if x != nil {
		if x.xxx_hidden_Names != nil {
			return *x.xxx_hidden_Names
		}
	}
	return nil
}

func (x *TopNamesResponse) SetNames(v []*TopName) {
	x.xxx_hidden_Names = &v
}

type TopNamesResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Names []*TopName
}

func (b0 TopNamesResponse_builder) Build() *TopNamesResponse {
	m0 := &TopNamesResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Names = &b.Names
	return m0
}

var File_number_v1_metrics_proto protoreflect.FileDescriptor

const file_number_v1_metrics_proto_rawDesc = "" +
	"\n" +
	"\x17number/v1/metrics.proto\x12\tnumber.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xde\x01\n" +
	"\x0eSummaryRequest\x120\n" +
	"\x05start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x03end:l\xbaHi\x1ag\n" +
	"\x0fend_after_start\x12\x17End must be after start\x1a;!has(this.end) || !has(this.start) || this.end > this.start\"\xb4\x01\n" +
	"\x0fSummaryResponse\x12\x1f\n" +
	"\vtotal_count\x18\x01 \x01(\x03R\n" +
	"totalCount\x12\x1b\n" +
	"\ttotal_sum\x18\x02 \x01(\x04R\btotalSum\x12\x18\n" +
	"\aaverage\x18\x03 \x01(\x01R\aaverage\x12\x10\n" +
	"\x03min\x18\x04 \x01(\rR\x03min\x12\x10\n" +
	"\x03max\x18\x05 \x01(\rR\x03max\x12%\n" +
	"\x0edistinct_names\x18\x06 \x01(\rR\rdistinctNames\"\xa2\x02\n" +
	"\x11TimeSeriesRequest\x12?\n" +
	"\binterval\x18\x01 \x01(\x0e2\x17.number.v1.TimeIntervalB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\binterval\x120\n" +
	"\x05start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x03end:l\xbaHi\x1ag\n" +
	"\x0fend_after_start\x12\x17End must be after start\x1a;!has(this.end) || !has(this.start) || this.end > this.start\"\x87\x01\n" +
	"\x0fTimeSeriesPoint\x122\n" +
	"\x06bucket\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x06bucket\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12\x10\n" +
	"\x03sum\x18\x03 \x01(\x04R\x03sum\x12\x18\n" +
	"\aaverage\x18\x04 \x01(\x01R\aaverage\"H\n" +
	"\x12TimeSeriesResponse\x122\n" +
	"\x06points\x18\x01 \x03(\v2\x1a.number.v1.TimeSeriesPointR\x06points\"\x91\x02\n" +
	"\x13DistributionRequest\x12,\n" +
	"\fbucket_count\x18\x01 \x01(\rB\t\xbaH\x06*\x04\x18d(\x01R\vbucketCount\x120\n" +
	"\x05start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x03end:l\xbaHi\x1ag\n" +
	"\x0fend_after_start\x12\x17End must be after start\x1a;!has(this.end) || !has(this.start) || this.end > this.start\"V\n" +
	"\x12DistributionBucket\x12\x14\n" +
	"\x05lower\x18\x01 \x01(\rR\x05lower\x12\x14\n" +
	"\x05upper\x18\x02 \x01(\rR\x05upper\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\"O\n" +
	"\x14DistributionResponse\x127\n" +
	"\abuckets\x18\x01 \x03(\v2\x1d.number.v1.DistributionBucketR\abuckets\"\x80\x02\n" +
	"\x0fTopNamesRequest\x12\x1f\n" +
	"\x05limit\x18\x01 \x01(\rB\t\xbaH\x06*\x04\x18d(\x01R\x05limit\x120\n" +
	"\x05start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x03end:l\xbaHi\x1ag\n" +
	"\x0fend_after_start\x12\x17End must be after start\x1a;!has(this.end) || !has(this.start) || this.end > this.start\"_\n" +
	"\aTopName\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12\x10\n" +
	"\x03sum\x18\x03 \x01(\x04R\x03sum\x12\x18\n" +
	"\aaverage\x18\x04 \x01(\x01R\aaverage\"<\n" +
	"\x10TopNamesResponse\x12(\n" +
	"\x05names\x18\x01 \x03(\v2\x12.number.v1.TopNameR\x05names*\x8d\x01\n" +
	"\fTimeInterval\x12\x1d\n" +
	"\x19TIME_INTERVAL_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TIME_INTERVAL_HOUR\x10\x01\x12\x15\n" +
	"\x11TIME_INTERVAL_DAY\x10\x02\x12\x16\n" +
	"\x12TIME_INTERVAL_WEEK\x10\x03\x12\x17\n" +
	"\x13TIME_INTERVAL_MONTH\x10\x04B\x99\x01\n" +
	"\rcom.number.v1B\fMetricsProtoP\x01Z5trev.zip/trev/stack/server/connect/number/v1;numberv1\xa2\x02\x03NXX\xaa\x02\tNumber.V1\xca\x02\tNumber\\V1\xe2\x02\x15Number\\V1\\GPBMetadata\xea\x02\n" +
	"Number::V1b\beditionsp\xe9\a"

var file_number_v1_metrics_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_number_v1_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_number_v1_metrics_proto_goTypes = []any{
	(TimeInterval)(0),             // 0: number.v1.TimeInterval
	(*SummaryRequest)(nil),        // 1: number.v1.SummaryRequest
	(*SummaryResponse)(nil),       // 2: number.v1.SummaryResponse
	(*TimeSeriesRequest)(nil),     // 3: number.v1.TimeSeriesRequest
	(*TimeSeriesPoint)(nil),       // 4: number.v1.TimeSeriesPoint
	(*TimeSeriesResponse)(nil),    // 5: number.v1.TimeSeriesResponse
	(*DistributionRequest)(nil),   // 6: number.v1.DistributionRequest
	(*DistributionBucket)(nil),    // 7: number.v1.DistributionBucket
	(*DistributionResponse)(nil),  // 8: number.v1.DistributionResponse
	(*TopNamesRequest)(nil),       // 9: number.v1.TopNamesRequest
	(*TopName)(nil),               // 10: number.v1.TopName
	(*TopNamesResponse)(nil),      // 11: number.v1.TopNamesResponse
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_number_v1_metrics_proto_depIdxs = []int32{
	12, // 0: number.v1.SummaryRequest.start:type_name -> google.protobuf.Timestamp
	12, // 1: number.v1.SummaryRequest.end:type_name -> google.protobuf.Timestamp
	0,  // 2: number.v1.TimeSeriesRequest.interval:type_name -> number.v1.TimeInterval
	12, // 3: number.v1.TimeSeriesRequest.start:type_name -> google.protobuf.Timestamp
	12, // 4: number.v1.TimeSeriesRequest.end:type_name -> google.protobuf.Timestamp
	12, // 5: number.v1.TimeSeriesPoint.bucket:type_name -> google.protobuf.Timestamp
	4,  // 6: number.v1.TimeSeriesResponse.points:type_name -> number.v1.TimeSeriesPoint
	12, // 7: number.v1.DistributionRequest.start:type_name -> google.protobuf.Timestamp
	12, // 8: number.v1.DistributionRequest.end:type_name -> google.protobuf.Timestamp
	7,  // 9: number.v1.DistributionResponse.buckets:type_name -> number.v1.DistributionBucket
	12, // 10: number.v1.TopNamesRequest.start:type_name -> google.protobuf.Timestamp
	12, // 11: number.v1.TopNamesRequest.end:type_name -> google.protobuf.Timestamp
	10, // 12: number.v1.TopNamesResponse.names:type_name -> number.v1.TopName
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_number_v1_metrics_proto_init() }
func file_number_v1_metrics_proto_init() {
	if File_number_v1_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_number_v1_metrics_proto_rawDesc), len(file_number_v1_metrics_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_number_v1_metrics_proto_goTypes,
		DependencyIndexes: file_number_v1_metrics_proto_depIdxs,
		EnumInfos:         file_number_v1_metrics_proto_enumTypes,
		MessageInfos:      file_number_v1_metrics_proto_msgTypes,
	}.Build()
	File_number_v1_metrics_proto = out.File
	file_number_v1_metrics_proto_goTypes = nil
	file_number_v1_metrics_proto_depIdxs = nil
}
