// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"time"
)

type File struct {
	ID     int64
	Name   string
	Data   []byte
	UserID int64
}

type Item struct {
	ID          int64
	Name        string
	Added       time.Time
	Description string
	Price       float64
	Quantity    int64
	UserID      int64
}

type SchemaMigration struct {
	Version string
}

type User struct {
	ID               int64
	Username         string
	Password         string
	ProfilePictureID *int64
}
