// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: auth/v1/login.proto

package authv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Username    *string                `protobuf:"bytes,1,opt,name=username,proto3,oneof"`
	xxx_hidden_Password    *string                `protobuf:"bytes,2,opt,name=password,proto3,oneof"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_auth_v1_login_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_login_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		if x.xxx_hidden_Username != nil {
			return *x.xxx_hidden_Username
		}
		return ""
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		if x.xxx_hidden_Password != nil {
			return *x.xxx_hidden_Password
		}
		return ""
	}
	return ""
}

func (x *LoginRequest) SetUsername(v string) {
	x.xxx_hidden_Username = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *LoginRequest) SetPassword(v string) {
	x.xxx_hidden_Password = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *LoginRequest) HasUsername() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *LoginRequest) HasPassword() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *LoginRequest) ClearUsername() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Username = nil
}

func (x *LoginRequest) ClearPassword() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Password = nil
}

type LoginRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Username *string
	Password *string
}

func (b0 LoginRequest_builder) Build() *LoginRequest {
	m0 := &LoginRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Username != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Username = b.Username
	}
	if b.Password != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Password = b.Password
	}
	return m0
}

type LoginResponse struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Jwt string                 `protobuf:"bytes,1,opt,name=jwt,proto3"`
	xxx_hidden_Sub string                 `protobuf:"bytes,2,opt,name=sub,proto3"`
	xxx_hidden_Exp int64                  `protobuf:"varint,3,opt,name=exp,proto3"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_auth_v1_login_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_login_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginResponse) GetJwt() string {
	if x != nil {
		return x.xxx_hidden_Jwt
	}
	return ""
}

func (x *LoginResponse) GetSub() string {
	if x != nil {
		return x.xxx_hidden_Sub
	}
	return ""
}

func (x *LoginResponse) GetExp() int64 {
	if x != nil {
		return x.xxx_hidden_Exp
	}
	return 0
}

func (x *LoginResponse) SetJwt(v string) {
	x.xxx_hidden_Jwt = v
}

func (x *LoginResponse) SetSub(v string) {
	x.xxx_hidden_Sub = v
}

func (x *LoginResponse) SetExp(v int64) {
	x.xxx_hidden_Exp = v
}

type LoginResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Jwt string
	// The canonical username used as the session token's subject.
	Sub string
	// The session token's expiration as a Unix timestamp in seconds.
	Exp int64
}

func (b0 LoginResponse_builder) Build() *LoginResponse {
	m0 := &LoginResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Jwt = b.Jwt
	x.xxx_hidden_Sub = b.Sub
	x.xxx_hidden_Exp = b.Exp
	return m0
}

var File_auth_v1_login_proto protoreflect.FileDescriptor

const file_auth_v1_login_proto_rawDesc = "" +
	"\n" +
	"\x13auth/v1/login.proto\x12\aauth.v1\x1a\x1bbuf/validate/validate.proto\"\xa3\x01\n" +
	"\fLoginRequest\x12J\n" +
	"\busername\x18\x01 \x01(\tB)\xbaH&\xc8\x01\x01r!\x10\x03\x18@2\x1b^[A-Za-z0-9][A-Za-z0-9_-]*$H\x00R\busername\x88\x01\x01\x12-\n" +
	"\bpassword\x18\x02 \x01(\tB\f\xbaH\t\xc8\x01\x01r\x04\x10\b(HH\x01R\bpassword\x88\x01\x01B\v\n" +
	"\t_usernameB\v\n" +
	"\t_password\"E\n" +
	"\rLoginResponse\x12\x10\n" +
	"\x03jwt\x18\x01 \x01(\tR\x03jwt\x12\x10\n" +
	"\x03sub\x18\x02 \x01(\tR\x03sub\x12\x10\n" +
	"\x03exp\x18\x03 \x01(\x03R\x03expB\x88\x01\n" +
	"\vcom.auth.v1B\n" +
	"LoginProtoP\x01Z0trev.zip/llc/stack/server/connect/auth/v1;authv1\xa2\x02\x03AXX\xaa\x02\aAuth.V1\xca\x02\aAuth\\V1\xe2\x02\x13Auth\\V1\\GPBMetadata\xea\x02\bAuth::V1b\x06proto3"

var file_auth_v1_login_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_auth_v1_login_proto_goTypes = []any{
	(*LoginRequest)(nil),  // 0: auth.v1.LoginRequest
	(*LoginResponse)(nil), // 1: auth.v1.LoginResponse
}
var file_auth_v1_login_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_v1_login_proto_init() }
func file_auth_v1_login_proto_init() {
	if File_auth_v1_login_proto != nil {
		return
	}
	file_auth_v1_login_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_login_proto_rawDesc), len(file_auth_v1_login_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_v1_login_proto_goTypes,
		DependencyIndexes: file_auth_v1_login_proto_depIdxs,
		MessageInfos:      file_auth_v1_login_proto_msgTypes,
	}.Build()
	File_auth_v1_login_proto = out.File
	file_auth_v1_login_proto_goTypes = nil
	file_auth_v1_login_proto_depIdxs = nil
}
