// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: auth/v1/service.proto

package authv1

import (
	_ "github.com/google/gnostic/openapiv3"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_auth_v1_service_proto protoreflect.FileDescriptor

const file_auth_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x15auth/v1/service.proto\x12\aauth.v1\x1a\x13auth/v1/login.proto\x1a\x14auth/v1/logout.proto\x1a\x14auth/v1/signup.proto\x1a$gnostic/openapi/v3/annotations.proto2\x8e\x02\n" +
	"\vAuthService\x12S\n" +
	"\x06Signup\x12\x16.auth.v1.SignupRequest\x1a\x17.auth.v1.SignupResponse\"\x18\xbaG\x15\x12\x11Create an accountZ\x00\x12N\n" +
	"\x05Login\x12\x15.auth.v1.LoginRequest\x1a\x16.auth.v1.LoginResponse\"\x16\xbaG\x13\x12\x0fStart a sessionZ\x00\x12Z\n" +
	"\x06Logout\x12\x16.auth.v1.LogoutRequest\x1a\x17.auth.v1.LogoutResponse\"\x1f\xbaG\x1c\x12\x18Clear the session cookieZ\x00B\x8f\x01\n" +
	"\vcom.auth.v1B\fServiceProtoP\x01Z5trev.zip/template/stack/server/connect/auth/v1;authv1\xa2\x02\x03AXX\xaa\x02\aAuth.V1\xca\x02\aAuth\\V1\xe2\x02\x13Auth\\V1\\GPBMetadata\xea\x02\bAuth::V1b\x06proto3"

var file_auth_v1_service_proto_goTypes = []any{
	(*SignupRequest)(nil),  // 0: auth.v1.SignupRequest
	(*LoginRequest)(nil),   // 1: auth.v1.LoginRequest
	(*LogoutRequest)(nil),  // 2: auth.v1.LogoutRequest
	(*SignupResponse)(nil), // 3: auth.v1.SignupResponse
	(*LoginResponse)(nil),  // 4: auth.v1.LoginResponse
	(*LogoutResponse)(nil), // 5: auth.v1.LogoutResponse
}
var file_auth_v1_service_proto_depIdxs = []int32{
	0, // 0: auth.v1.AuthService.Signup:input_type -> auth.v1.SignupRequest
	1, // 1: auth.v1.AuthService.Login:input_type -> auth.v1.LoginRequest
	2, // 2: auth.v1.AuthService.Logout:input_type -> auth.v1.LogoutRequest
	3, // 3: auth.v1.AuthService.Signup:output_type -> auth.v1.SignupResponse
	4, // 4: auth.v1.AuthService.Login:output_type -> auth.v1.LoginResponse
	5, // 5: auth.v1.AuthService.Logout:output_type -> auth.v1.LogoutResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_v1_service_proto_init() }
func file_auth_v1_service_proto_init() {
	if File_auth_v1_service_proto != nil {
		return
	}
	file_auth_v1_login_proto_init()
	file_auth_v1_logout_proto_init()
	file_auth_v1_signup_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_service_proto_rawDesc), len(file_auth_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_v1_service_proto_goTypes,
		DependencyIndexes: file_auth_v1_service_proto_depIdxs,
	}.Build()
	File_auth_v1_service_proto = out.File
	file_auth_v1_service_proto_goTypes = nil
	file_auth_v1_service_proto_depIdxs = nil
}
