// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file number/v1/list.proto (package number.v1, edition 2024)
/* eslint-disable */

import type { Message } from "@bufbuild/protobuf";
import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

import { file_buf_validate_validate } from "../../buf/validate/validate_pb";

/**
 * Describes the file number/v1/list.proto.
 */
export const file_number_v1_list: GenFile /*@__PURE__*/ = fileDesc(
  "ChRudW1iZXIvdjEvbGlzdC5wcm90bxIJbnVtYmVyLnYxImsKBEl0ZW0SLQoJdGltZXN0YW1wGAEgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIXCgRuYW1lGAIgASgJQgm6SAZyBBABGDISGwoGbnVtYmVyGAMgASgNQgu6SAgqBhjAhD0oACKwAwoLTGlzdFJlcXVlc3QSFwoEbmFtZRgBIAEoCUIJukgGcgQQABgyEhwKB21pbmltdW0YAiABKA1CC7pICCoGGMCEPSgAEhwKB21heGltdW0YAyABKA1CC7pICCoGGMCEPSgAEikKBXN0YXJ0GAQgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBInCgNlbmQYBSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wOvcBukjzARpnCg9lbmRfYWZ0ZXJfc3RhcnQSF0VuZCBtdXN0IGJlIGFmdGVyIHN0YXJ0GjshaGFzKHRoaXMuZW5kKSB8fCAhaGFzKHRoaXMuc3RhcnQpIHx8IHRoaXMuZW5kID4gdGhpcy5zdGFydBqHAQoZbWluaW11bV9sZXNzX3RoYW5fbWF4aW11bRIhTWluaW11bSBtdXN0IGJlIGxlc3MgdGhhbiBtYXhpbXVtGkchaGFzKHRoaXMubWluaW11bSkgfHwgIWhhcyh0aGlzLm1heGltdW0pIHx8IHRoaXMubWluaW11bSA8IHRoaXMubWF4aW11bSItCgxMaXN0UmVzcG9uc2USHQoEaXRlbRgBIAEoCzIPLm51bWJlci52MS5JdGVtQqEBCg1jb20ubnVtYmVyLnYxQglMaXN0UHJvdG9QAVpAZ2l0aHViLmNvbS9zcG90ZGVtbzQvdHJldnN0YWNrL3NlcnZlci9jb25uZWN0L251bWJlci92MTtudW1iZXJ2MaICA05YWKoCCU51bWJlci5WMcoCCU51bWJlclxWMeICFU51bWJlclxWMVxHUEJNZXRhZGF0YeoCCk51bWJlcjo6VjFiCGVkaXRpb25zcOkH",
  [file_buf_validate_validate, file_google_protobuf_timestamp],
);

/**
 * @generated from message number.v1.Item
 */
export type Item = Message<"number.v1.Item"> & {
  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 1;
   */
  timestamp?: Timestamp;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: uint32 number = 3;
   */
  number: number;
};

/**
 * Describes the message number.v1.Item.
 * Use `create(ItemSchema)` to create a new message.
 */
export const ItemSchema: GenMessage<Item> /*@__PURE__*/ = messageDesc(file_number_v1_list, 0);

/**
 * @generated from message number.v1.ListRequest
 */
export type ListRequest = Message<"number.v1.ListRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: uint32 minimum = 2;
   */
  minimum: number;

  /**
   * @generated from field: uint32 maximum = 3;
   */
  maximum: number;

  /**
   * @generated from field: google.protobuf.Timestamp start = 4;
   */
  start?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp end = 5;
   */
  end?: Timestamp;
};

/**
 * Describes the message number.v1.ListRequest.
 * Use `create(ListRequestSchema)` to create a new message.
 */
export const ListRequestSchema: GenMessage<ListRequest> /*@__PURE__*/ = messageDesc(
  file_number_v1_list,
  1,
);

/**
 * @generated from message number.v1.ListResponse
 */
export type ListResponse = Message<"number.v1.ListResponse"> & {
  /**
   * @generated from field: number.v1.Item item = 1;
   */
  item?: Item;
};

/**
 * Describes the message number.v1.ListResponse.
 * Use `create(ListResponseSchema)` to create a new message.
 */
export const ListResponseSchema: GenMessage<ListResponse> /*@__PURE__*/ = messageDesc(
  file_number_v1_list,
  2,
);
