// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file number/v1/list.proto (package number.v1, edition 2024)
/* eslint-disable */

import type { Message } from "@bufbuild/protobuf";
import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

import { file_buf_validate_validate } from "../../buf/validate/validate_pb";

/**
 * Describes the file number/v1/list.proto.
 */
export const file_number_v1_list: GenFile /*@__PURE__*/ = fileDesc(
  "ChRudW1iZXIvdjEvbGlzdC5wcm90bxIJbnVtYmVyLnYxImsKBEl0ZW0SLQoJdGltZXN0YW1wGAEgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIXCgRuYW1lGAIgASgJQgm6SAZyBBABGDISGwoGbnVtYmVyGAMgASgNQgu6SAgqBhjAhD0oACKHAwoLTGlzdFJlcXVlc3QSFwoEbmFtZRgBIAEoCUIJukgGcgQQABgyEhgKA21pbhgCIAEoDUILukgIKgYYwIQ9KAASGAoDbWF4GAMgASgNQgu6SAgqBhjAhD0oABIpCgVzdGFydBgEIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASJwoDZW5kGAUgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcDrWAbpI0gEaZwoPZW5kX2FmdGVyX3N0YXJ0EhdFbmQgbXVzdCBiZSBhZnRlciBzdGFydBo7IWhhcyh0aGlzLmVuZCkgfHwgIWhhcyh0aGlzLnN0YXJ0KSB8fCB0aGlzLmVuZCA+IHRoaXMuc3RhcnQaZwoRbWluX2xlc3NfdGhhbl9tYXgSGU1pbiBtdXN0IGJlIGxlc3MgdGhhbiBtYXgaNyFoYXModGhpcy5taW4pIHx8ICFoYXModGhpcy5tYXgpIHx8IHRoaXMubWluIDwgdGhpcy5tYXgiLQoMTGlzdFJlc3BvbnNlEh0KBGl0ZW0YASABKAsyDy5udW1iZXIudjEuSXRlbUKhAQoNY29tLm51bWJlci52MUIJTGlzdFByb3RvUAFaQGdpdGh1Yi5jb20vc3BvdGRlbW80L3RyZXZzdGFjay9zZXJ2ZXIvY29ubmVjdC9udW1iZXIvdjE7bnVtYmVydjGiAgNOWFiqAglOdW1iZXIuVjHKAglOdW1iZXJcVjHiAhVOdW1iZXJcVjFcR1BCTWV0YWRhdGHqAgpOdW1iZXI6OlYxYghlZGl0aW9uc3DpBw",
  [file_buf_validate_validate, file_google_protobuf_timestamp],
);

/**
 * @generated from message number.v1.Item
 */
export type Item = Message<"number.v1.Item"> & {
  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 1;
   */
  timestamp?: Timestamp;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: uint32 number = 3;
   */
  number: number;
};

/**
 * Describes the message number.v1.Item.
 * Use `create(ItemSchema)` to create a new message.
 */
export const ItemSchema: GenMessage<Item> /*@__PURE__*/ = messageDesc(file_number_v1_list, 0);

/**
 * @generated from message number.v1.ListRequest
 */
export type ListRequest = Message<"number.v1.ListRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: uint32 min = 2;
   */
  min: number;

  /**
   * @generated from field: uint32 max = 3;
   */
  max: number;

  /**
   * @generated from field: google.protobuf.Timestamp start = 4;
   */
  start?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp end = 5;
   */
  end?: Timestamp;
};

/**
 * Describes the message number.v1.ListRequest.
 * Use `create(ListRequestSchema)` to create a new message.
 */
export const ListRequestSchema: GenMessage<ListRequest> /*@__PURE__*/ = messageDesc(
  file_number_v1_list,
  1,
);

/**
 * @generated from message number.v1.ListResponse
 */
export type ListResponse = Message<"number.v1.ListResponse"> & {
  /**
   * @generated from field: number.v1.Item item = 1;
   */
  item?: Item;
};

/**
 * Describes the message number.v1.ListResponse.
 * Use `create(ListResponseSchema)` to create a new message.
 */
export const ListResponseSchema: GenMessage<ListResponse> /*@__PURE__*/ = messageDesc(
  file_number_v1_list,
  2,
);
