// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file number/v1/list.proto (package number.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file number/v1/list.proto.
 */
export const file_number_v1_list: GenFile = /*@__PURE__*/
  fileDesc("ChRudW1iZXIvdjEvbGlzdC5wcm90bxIJbnVtYmVyLnYxImsKBEl0ZW0SLQoJdGltZXN0YW1wGAEgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIXCgRuYW1lGAIgASgJQgm6SAZyBBABGDISGwoGbnVtYmVyGAMgASgNQgu6SAgqBhjAhD0oACLaAgoLTGlzdFJlcXVlc3QSEwoGY3Vyc29yGAEgASgDSACIAQESHAoEbmFtZRgCIAEoCUIJukgGcgQQARgySAGIAQESHQoDbWluGAMgASgNQgu6SAgqBhjAhD0oAEgCiAEBEh0KA21heBgEIAEoDUILukgIKgYYwIQ9KABIA4gBARIuCgVzdGFydBgFIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBIBIgBARIsCgNlbmQYBiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wSAWIAQE6RrpIQxpBCg9lbmRfYWZ0ZXJfc3RhcnQSF0VuZCBtdXN0IGJlIGFmdGVyIHN0YXJ0GhV0aGlzLmVuZCA+IHRoaXMuc3RhcnRCCQoHX2N1cnNvckIHCgVfbmFtZUIGCgRfbWluQgYKBF9tYXhCCAoGX3N0YXJ0QgYKBF9lbmQiWAoMTGlzdFJlc3BvbnNlEh4KBWl0ZW1zGAEgAygLMg8ubnVtYmVyLnYxLkl0ZW0SGAoLbmV4dF9jdXJzb3IYAiABKANIAIgBAUIOCgxfbmV4dF9jdXJzb3JCoQEKDWNvbS5udW1iZXIudjFCCUxpc3RQcm90b1ABWkBnaXRodWIuY29tL3Nwb3RkZW1vNC90cmV2c3RhY2svc2VydmVyL2Nvbm5lY3QvbnVtYmVyL3YxO251bWJlcnYxogIDTlhYqgIJTnVtYmVyLlYxygIJTnVtYmVyXFYx4gIVTnVtYmVyXFYxXEdQQk1ldGFkYXRh6gIKTnVtYmVyOjpWMWIGcHJvdG8z", [file_buf_validate_validate, file_google_protobuf_timestamp]);

/**
 * @generated from message number.v1.Item
 */
export type Item = Message<"number.v1.Item"> & {
  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 1;
   */
  timestamp?: Timestamp;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: uint32 number = 3;
   */
  number: number;
};

/**
 * Describes the message number.v1.Item.
 * Use `create(ItemSchema)` to create a new message.
 */
export const ItemSchema: GenMessage<Item> = /*@__PURE__*/
  messageDesc(file_number_v1_list, 0);

/**
 * @generated from message number.v1.ListRequest
 */
export type ListRequest = Message<"number.v1.ListRequest"> & {
  /**
   * @generated from field: optional int64 cursor = 1;
   */
  cursor?: bigint;

  /**
   * @generated from field: optional string name = 2;
   */
  name?: string;

  /**
   * @generated from field: optional uint32 min = 3;
   */
  min?: number;

  /**
   * @generated from field: optional uint32 max = 4;
   */
  max?: number;

  /**
   * @generated from field: optional google.protobuf.Timestamp start = 5;
   */
  start?: Timestamp;

  /**
   * @generated from field: optional google.protobuf.Timestamp end = 6;
   */
  end?: Timestamp;
};

/**
 * Describes the message number.v1.ListRequest.
 * Use `create(ListRequestSchema)` to create a new message.
 */
export const ListRequestSchema: GenMessage<ListRequest> = /*@__PURE__*/
  messageDesc(file_number_v1_list, 1);

/**
 * @generated from message number.v1.ListResponse
 */
export type ListResponse = Message<"number.v1.ListResponse"> & {
  /**
   * @generated from field: repeated number.v1.Item items = 1;
   */
  items: Item[];

  /**
   * @generated from field: optional int64 next_cursor = 2;
   */
  nextCursor?: bigint;
};

/**
 * Describes the message number.v1.ListResponse.
 * Use `create(ListResponseSchema)` to create a new message.
 */
export const ListResponseSchema: GenMessage<ListResponse> = /*@__PURE__*/
  messageDesc(file_number_v1_list, 2);

