// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file number/v1/service.proto (package number.v1, edition 2024)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";

import type { AddRequestSchema, AddResponseSchema } from "./add_pb";
import { file_number_v1_add } from "./add_pb";
import type { ListRequestSchema, ListResponseSchema } from "./list_pb";
import { file_number_v1_list } from "./list_pb";
import type {
  DistributionRequestSchema,
  DistributionResponseSchema,
  SummaryRequestSchema,
  SummaryResponseSchema,
  TimeSeriesRequestSchema,
  TimeSeriesResponseSchema,
  TopNamesRequestSchema,
  TopNamesResponseSchema,
} from "./metrics_pb";
import { file_number_v1_metrics } from "./metrics_pb";

/**
 * Describes the file number/v1/service.proto.
 */
export const file_number_v1_service: GenFile /*@__PURE__*/ = fileDesc(
  "ChdudW1iZXIvdjEvc2VydmljZS5wcm90bxIJbnVtYmVyLnYxMq8DCg1OdW1iZXJTZXJ2aWNlEjYKA0FkZBIVLm51bWJlci52MS5BZGRSZXF1ZXN0GhYubnVtYmVyLnYxLkFkZFJlc3BvbnNlIgASOwoETGlzdBIWLm51bWJlci52MS5MaXN0UmVxdWVzdBoXLm51bWJlci52MS5MaXN0UmVzcG9uc2UiADABEkIKB1N1bW1hcnkSGS5udW1iZXIudjEuU3VtbWFyeVJlcXVlc3QaGi5udW1iZXIudjEuU3VtbWFyeVJlc3BvbnNlIgASSwoKVGltZVNlcmllcxIcLm51bWJlci52MS5UaW1lU2VyaWVzUmVxdWVzdBodLm51bWJlci52MS5UaW1lU2VyaWVzUmVzcG9uc2UiABJRCgxEaXN0cmlidXRpb24SHi5udW1iZXIudjEuRGlzdHJpYnV0aW9uUmVxdWVzdBofLm51bWJlci52MS5EaXN0cmlidXRpb25SZXNwb25zZSIAEkUKCFRvcE5hbWVzEhoubnVtYmVyLnYxLlRvcE5hbWVzUmVxdWVzdBobLm51bWJlci52MS5Ub3BOYW1lc1Jlc3BvbnNlIgBCmAEKDWNvbS5udW1iZXIudjFCDFNlcnZpY2VQcm90b1ABWjR0cmV2LnppcC9sbGMvc3RhY2svc2VydmVyL2Nvbm5lY3QvbnVtYmVyL3YxO251bWJlcnYxogIDTlhYqgIJTnVtYmVyLlYxygIJTnVtYmVyXFYx4gIVTnVtYmVyXFYxXEdQQk1ldGFkYXRh6gIKTnVtYmVyOjpWMWIIZWRpdGlvbnNw6Qc",
  [file_number_v1_add, file_number_v1_list, file_number_v1_metrics],
);

/**
 * @generated from service number.v1.NumberService
 */
export const NumberService: GenService<{
  /**
   * @generated from rpc number.v1.NumberService.Add
   */
  add: {
    methodKind: "unary";
    input: typeof AddRequestSchema;
    output: typeof AddResponseSchema;
  };
  /**
   * @generated from rpc number.v1.NumberService.List
   */
  list: {
    methodKind: "server_streaming";
    input: typeof ListRequestSchema;
    output: typeof ListResponseSchema;
  };
  /**
   * @generated from rpc number.v1.NumberService.Summary
   */
  summary: {
    methodKind: "unary";
    input: typeof SummaryRequestSchema;
    output: typeof SummaryResponseSchema;
  };
  /**
   * @generated from rpc number.v1.NumberService.TimeSeries
   */
  timeSeries: {
    methodKind: "unary";
    input: typeof TimeSeriesRequestSchema;
    output: typeof TimeSeriesResponseSchema;
  };
  /**
   * @generated from rpc number.v1.NumberService.Distribution
   */
  distribution: {
    methodKind: "unary";
    input: typeof DistributionRequestSchema;
    output: typeof DistributionResponseSchema;
  };
  /**
   * @generated from rpc number.v1.NumberService.TopNames
   */
  topNames: {
    methodKind: "unary";
    input: typeof TopNamesRequestSchema;
    output: typeof TopNamesResponseSchema;
  };
}> /*@__PURE__*/ = serviceDesc(file_number_v1_service, 0);
