// @generated
// This file is @generated by prost-build.
/// Credentials for an existing account.
///
/// Example (protobuf JSON):
/// ```json
/// {"username": "demo_user", "password": "example-password"}
/// ```
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginRequest {
    #[prost(string, optional, tag = "1")]
    pub username: ::core::option::Option<::prost::alloc::string::String>,
    /// Account password; accepted as input and never returned in a response.
    #[prost(string, optional, tag = "2")]
    pub password: ::core::option::Option<::prost::alloc::string::String>,
}
/// Session token and metadata returned after successful authentication.
/// The example token is a placeholder, not a usable JWT.
///
/// Example (protobuf JSON):
/// ```json
/// {"jwt": "example-session-token", "sub": "demo_user", "exp": "1893456000"}
/// ```
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginResponse {
    /// Signed session token.
    #[prost(string, tag = "1")]
    pub jwt: ::prost::alloc::string::String,
    /// The canonical username used as the session token's subject.
    #[prost(string, tag = "2")]
    pub sub: ::prost::alloc::string::String,
    /// The session token's expiration as Unix seconds, encoded as a decimal string in protobuf JSON.
    #[prost(int64, tag = "3")]
    pub exp: i64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LogoutRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LogoutResponse {}
/// Credentials for a new account.
///
/// Example (protobuf JSON):
/// ```json
/// {"username": "demo_user", "password": "example-password"}
/// ```
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SignupRequest {
    #[prost(string, optional, tag = "1")]
    pub username: ::core::option::Option<::prost::alloc::string::String>,
    /// Account password; accepted as input and never returned in a response.
    #[prost(string, optional, tag = "2")]
    pub password: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SignupResponse {}
include!("auth.v1.tonic.rs");
// @@protoc_insertion_point(module)
