// @generated
// This file is @generated by prost-build.
/// A named positive value to record.
///
/// Example (protobuf JSON):
/// ```json
/// {"name": "visits", "number": 7}
/// ```
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AddRequest {
    #[prost(string, optional, tag = "1")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag = "2")]
    pub number: ::core::option::Option<u32>,
}
/// Example (protobuf JSON):
/// ```json
/// {"sum": "42"}
/// ```
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AddResponse {
    /// Sum of all stored numbers after this addition, encoded as a decimal string in protobuf JSON.
    #[prost(uint64, tag = "1")]
    pub sum: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Item {
    #[prost(message, optional, tag = "1")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub number: u32,
}
/// Optional filters for the item stream. Timestamps use RFC 3339 strings in protobuf JSON.
///
/// Example (protobuf JSON):
/// ```json
/// {"name": "visits", "minimum": 1, "maximum": 100, "start": "2026-09-01T00:00:00Z", "end": "2026-10-01T00:00:00Z"}
/// ```
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListRequest {
    #[prost(string, optional, tag = "1")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag = "2")]
    pub minimum: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "3")]
    pub maximum: ::core::option::Option<u32>,
    #[prost(message, optional, tag = "4")]
    pub start: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "5")]
    pub end: ::core::option::Option<::prost_types::Timestamp>,
}
/// One matching item in the server stream, not an array of results.
///
/// Example (protobuf JSON):
/// ```json
/// {"item": {"timestamp": "2026-09-20T12:00:00Z", "name": "visits", "number": 7}}
/// ```
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListResponse {
    #[prost(message, optional, tag = "1")]
    pub item: ::core::option::Option<Item>,
}
/// Scalar summary metrics across all items, suitable for stat cards.
///
/// Example (protobuf JSON):
/// ```json
/// {"start": "2026-09-01T00:00:00Z", "end": "2026-10-01T00:00:00Z"}
/// ```
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SummaryRequest {
    /// Inclusive lower timestamp bound; omit for no lower bound.
    #[prost(message, optional, tag = "1")]
    pub start: ::core::option::Option<::prost_types::Timestamp>,
    /// Inclusive upper timestamp bound; omit for no upper bound.
    #[prost(message, optional, tag = "2")]
    pub end: ::core::option::Option<::prost_types::Timestamp>,
}
/// Counts and sums use decimal strings for 64-bit integers in protobuf JSON.
///
/// Example (protobuf JSON):
/// ```json
/// {"totalCount": "3", "totalSum": "42", "average": 14, "min": 7, "max": 21, "distinctNames": 2}
/// ```
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SummaryResponse {
    #[prost(int64, tag = "1")]
    pub total_count: i64,
    #[prost(uint64, tag = "2")]
    pub total_sum: u64,
    #[prost(double, tag = "3")]
    pub average: f64,
    #[prost(uint32, tag = "4")]
    pub min: u32,
    #[prost(uint32, tag = "5")]
    pub max: u32,
    #[prost(uint32, tag = "6")]
    pub distinct_names: u32,
}
/// Selects the UTC bucket interval and optional time range.
///
/// Example (protobuf JSON):
/// ```json
/// {"interval": "TIME_INTERVAL_DAY", "start": "2026-09-01T00:00:00Z", "end": "2026-10-01T00:00:00Z"}
/// ```
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TimeSeriesRequest {
    #[prost(enumeration = "TimeInterval", optional, tag = "1")]
    pub interval: ::core::option::Option<i32>,
    /// Inclusive lower timestamp bound; omit for no lower bound.
    #[prost(message, optional, tag = "2")]
    pub start: ::core::option::Option<::prost_types::Timestamp>,
    /// Inclusive upper timestamp bound; omit for no upper bound.
    #[prost(message, optional, tag = "3")]
    pub end: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TimeSeriesPoint {
    #[prost(message, optional, tag = "1")]
    pub bucket: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(int64, tag = "2")]
    pub count: i64,
    #[prost(uint64, tag = "3")]
    pub sum: u64,
    #[prost(double, tag = "4")]
    pub average: f64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TimeSeriesResponse {
    #[prost(message, repeated, tag = "1")]
    pub points: ::prost::alloc::vec::Vec<TimeSeriesPoint>,
}
/// Histogram of `number` values across approximately equal-width buckets, suitable for bar charts.
///
/// Example (protobuf JSON):
/// ```json
/// {"bucketCount": 10, "start": "2026-09-01T00:00:00Z", "end": "2026-10-01T00:00:00Z"}
/// ```
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DistributionRequest {
    #[prost(uint32, optional, tag = "1")]
    pub bucket_count: ::core::option::Option<u32>,
    /// Inclusive lower timestamp bound; omit for no lower bound.
    #[prost(message, optional, tag = "2")]
    pub start: ::core::option::Option<::prost_types::Timestamp>,
    /// Inclusive upper timestamp bound; omit for no upper bound.
    #[prost(message, optional, tag = "3")]
    pub end: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DistributionBucket {
    #[prost(uint32, tag = "1")]
    pub lower: u32,
    #[prost(uint32, tag = "2")]
    pub upper: u32,
    #[prost(int64, tag = "3")]
    pub count: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DistributionResponse {
    #[prost(message, repeated, tag = "1")]
    pub buckets: ::prost::alloc::vec::Vec<DistributionBucket>,
}
/// Top N names by frequency and total value, suitable for bar/pie charts.
///
/// Example (protobuf JSON):
/// ```json
/// {"limit": 5, "start": "2026-09-01T00:00:00Z", "end": "2026-10-01T00:00:00Z"}
/// ```
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TopNamesRequest {
    #[prost(uint32, optional, tag = "1")]
    pub limit: ::core::option::Option<u32>,
    /// Inclusive lower timestamp bound; omit for no lower bound.
    #[prost(message, optional, tag = "2")]
    pub start: ::core::option::Option<::prost_types::Timestamp>,
    /// Inclusive upper timestamp bound; omit for no upper bound.
    #[prost(message, optional, tag = "3")]
    pub end: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TopName {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub count: i64,
    #[prost(uint64, tag = "3")]
    pub sum: u64,
    #[prost(double, tag = "4")]
    pub average: f64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TopNamesResponse {
    #[prost(message, repeated, tag = "1")]
    pub names: ::prost::alloc::vec::Vec<TopName>,
}
/// Time-bucketed counts and sums, suitable for line/area charts.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TimeInterval {
    Unspecified = 0,
    Hour = 1,
    Day = 2,
    Week = 3,
    Month = 4,
}
impl TimeInterval {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "TIME_INTERVAL_UNSPECIFIED",
            Self::Hour => "TIME_INTERVAL_HOUR",
            Self::Day => "TIME_INTERVAL_DAY",
            Self::Week => "TIME_INTERVAL_WEEK",
            Self::Month => "TIME_INTERVAL_MONTH",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TIME_INTERVAL_UNSPECIFIED" => Some(Self::Unspecified),
            "TIME_INTERVAL_HOUR" => Some(Self::Hour),
            "TIME_INTERVAL_DAY" => Some(Self::Day),
            "TIME_INTERVAL_WEEK" => Some(Self::Week),
            "TIME_INTERVAL_MONTH" => Some(Self::Month),
            _ => None,
        }
    }
}
include!("number.v1.tonic.rs");
// @@protoc_insertion_point(module)
