// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file auth/v1/check_session.proto (package auth.v1, syntax proto3)
/* eslint-disable */

import type { Message } from "@bufbuild/protobuf";
import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file auth/v1/check_session.proto.
 */
export const file_auth_v1_check_session: GenFile /*@__PURE__*/ = fileDesc(
  "ChthdXRoL3YxL2NoZWNrX3Nlc3Npb24ucHJvdG8SB2F1dGgudjEiFQoTQ2hlY2tTZXNzaW9uUmVxdWVzdCIWChRDaGVja1Nlc3Npb25SZXNwb25zZUKPAQoLY29tLmF1dGgudjFCEUNoZWNrU2Vzc2lvblByb3RvUAFaMHRyZXYuemlwL2xsYy9zdGFjay9zZXJ2ZXIvY29ubmVjdC9hdXRoL3YxO2F1dGh2MaICA0FYWKoCB0F1dGguVjHKAgdBdXRoXFYx4gITQXV0aFxWMVxHUEJNZXRhZGF0YeoCCEF1dGg6OlYxYgZwcm90bzM",
);

/**
 * @generated from message auth.v1.CheckSessionRequest
 */
export type CheckSessionRequest = Message<"auth.v1.CheckSessionRequest"> & {};

/**
 * Describes the message auth.v1.CheckSessionRequest.
 * Use `create(CheckSessionRequestSchema)` to create a new message.
 */
export const CheckSessionRequestSchema: GenMessage<CheckSessionRequest> /*@__PURE__*/ = messageDesc(
  file_auth_v1_check_session,
  0,
);

/**
 * @generated from message auth.v1.CheckSessionResponse
 */
export type CheckSessionResponse = Message<"auth.v1.CheckSessionResponse"> & {};

/**
 * Describes the message auth.v1.CheckSessionResponse.
 * Use `create(CheckSessionResponseSchema)` to create a new message.
 */
export const CheckSessionResponseSchema: GenMessage<CheckSessionResponse> /*@__PURE__*/ =
  messageDesc(file_auth_v1_check_session, 1);
