// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file auth/v1/signup.proto (package auth.v1, syntax proto3)
/* eslint-disable */

import type { Message } from "@bufbuild/protobuf";
import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import { file_gnostic_openapi_v3_annotations } from "../../gnostic/openapi/v3/annotations_pb";

/**
 * Describes the file auth/v1/signup.proto.
 */
export const file_auth_v1_signup: GenFile /*@__PURE__*/ = fileDesc(
  "ChRhdXRoL3YxL3NpZ251cC5wcm90bxIHYXV0aC52MSLEAQoNU2lnbnVwUmVxdWVzdBJQCgh1c2VybmFtZRgBIAEoCUI5ukcNOgsSCWRlbW9fdXNlcrpIJsgBAXIhEAMYQDIbXltBLVphLXowLTldW0EtWmEtejAtOV8tXSokSACIAQESRwoIcGFzc3dvcmQYAiABKAlCMLpHISABOhISEGV4YW1wbGUtcGFzc3dvcmSaAghwYXNzd29yZLpICcgBAXIEEAgoSEgBiAEBQgsKCV91c2VybmFtZUILCglfcGFzc3dvcmQiEAoOU2lnbnVwUmVzcG9uc2VCiQEKC2NvbS5hdXRoLnYxQgtTaWdudXBQcm90b1ABWjB0cmV2LnppcC9sbGMvc3RhY2svc2VydmVyL2Nvbm5lY3QvYXV0aC92MTthdXRodjGiAgNBWFiqAgdBdXRoLlYxygIHQXV0aFxWMeICE0F1dGhcVjFcR1BCTWV0YWRhdGHqAghBdXRoOjpWMWIGcHJvdG8z",
  [file_buf_validate_validate, file_gnostic_openapi_v3_annotations],
);

/**
 * Credentials for a new account.
 *
 * Example (protobuf JSON):
 * ```json
 * {"username": "demo_user", "password": "example-password"}
 * ```
 *
 * @generated from message auth.v1.SignupRequest
 */
export type SignupRequest = Message<"auth.v1.SignupRequest"> & {
  /**
   * @generated from field: optional string username = 1;
   */
  username?: string | undefined;

  /**
   * Account password; accepted as input and never returned in a response.
   *
   * @generated from field: optional string password = 2;
   */
  password?: string | undefined;
};

/**
 * Describes the message auth.v1.SignupRequest.
 * Use `create(SignupRequestSchema)` to create a new message.
 */
export const SignupRequestSchema: GenMessage<SignupRequest> /*@__PURE__*/ = messageDesc(
  file_auth_v1_signup,
  0,
);

/**
 * @generated from message auth.v1.SignupResponse
 */
export type SignupResponse = Message<"auth.v1.SignupResponse"> & {};

/**
 * Describes the message auth.v1.SignupResponse.
 * Use `create(SignupResponseSchema)` to create a new message.
 */
export const SignupResponseSchema: GenMessage<SignupResponse> /*@__PURE__*/ = messageDesc(
  file_auth_v1_signup,
  1,
);
