// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file auth/v1/signup.proto (package auth.v1, syntax proto3)
/* eslint-disable */

import type { Message } from "@bufbuild/protobuf";
import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

import { file_buf_validate_validate } from "../../buf/validate/validate_pb";

/**
 * Describes the file auth/v1/signup.proto.
 */
export const file_auth_v1_signup: GenFile /*@__PURE__*/ = fileDesc(
  "ChRhdXRoL3YxL3NpZ251cC5wcm90bxIHYXV0aC52MSKQAQoNU2lnbnVwUmVxdWVzdBJACgh1c2VybmFtZRgBIAEoCUIpukgmyAEBciEQAxhAMhteW0EtWmEtejAtOV1bQS1aYS16MC05Xy1dKiRIAIgBARIjCghwYXNzd29yZBgCIAEoCUIMukgJyAEBcgQQCChISAGIAQFCCwoJX3VzZXJuYW1lQgsKCV9wYXNzd29yZCIQCg5TaWdudXBSZXNwb25zZUKJAQoLY29tLmF1dGgudjFCC1NpZ251cFByb3RvUAFaMHRyZXYuemlwL2xsYy9zdGFjay9zZXJ2ZXIvY29ubmVjdC9hdXRoL3YxO2F1dGh2MaICA0FYWKoCB0F1dGguVjHKAgdBdXRoXFYx4gITQXV0aFxWMVxHUEJNZXRhZGF0YeoCCEF1dGg6OlYxYgZwcm90bzM",
  [file_buf_validate_validate],
);

/**
 * @generated from message auth.v1.SignupRequest
 */
export type SignupRequest = Message<"auth.v1.SignupRequest"> & {
  /**
   * @generated from field: optional string username = 1;
   */
  username?: string | undefined;

  /**
   * @generated from field: optional string password = 2;
   */
  password?: string | undefined;
};

/**
 * Describes the message auth.v1.SignupRequest.
 * Use `create(SignupRequestSchema)` to create a new message.
 */
export const SignupRequestSchema: GenMessage<SignupRequest> /*@__PURE__*/ = messageDesc(
  file_auth_v1_signup,
  0,
);

/**
 * @generated from message auth.v1.SignupResponse
 */
export type SignupResponse = Message<"auth.v1.SignupResponse"> & {};

/**
 * Describes the message auth.v1.SignupResponse.
 * Use `create(SignupResponseSchema)` to create a new message.
 */
export const SignupResponseSchema: GenMessage<SignupResponse> /*@__PURE__*/ = messageDesc(
  file_auth_v1_signup,
  1,
);
