name: "Initialize"
description: "Install nix & use cachix"

inputs:
  token:
    description: "cachix auth token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install nix
      uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Use cachix
      uses: cachix/cachix-action@v16
      with:
        name: trevstack
        authToken: "${{ inputs.token }}"
