name: "Initialize"
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Use Cachix
      uses: cachix/cachix-action@v16
      with:
        name: trevstack
        authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
