name: "initialize"
runs:
  using: "composite"
  steps:
    - name: install nix
      uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: use cachix
      uses: cachix/cachix-action@v16
      with:
        name: trevstack
        authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
