name: Lint Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Use Cachix
        uses: cachix/cachix-action@v16
        with:
          name: trevstack
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Install NPM Packages
        working-directory: ./client
        run: npm ci --legacy-peer-deps
        
      - name: Lint
        run: nix develop --command ts-lint