name: Lint Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Use Cachix
        uses: cachix/cachix-action@v16
        with:
          name: trevstack
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Install NPM Packages
        working-directory: ./client
        run: npm i && npm ci # https://github.com/npm/cli/issues/6787#issuecomment-2128344748

      - uses: nicknovitski/nix-develop@v1
        
      - run: npx prettier --check .
        working-directory: ./client

      - run: npx eslint .
        working-directory: ./client

      - run: npx svelte-check
        working-directory: ./client

      - run: revive -config revive.toml -set_exit_status ./...
        working-directory: ./server

      - run: sqlfluff lint
        working-directory: ./server

      - run: buf lint

      - run: nix fmt -- flake.nix --check

      - run: nix flake check --all-systems