name: Release Workflow

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
        
      - name: Build
        run: nix develop --command ts-build

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |-
            build/**