name: Update Workflow

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Use Cachix
        uses: cachix/cachix-action@v16
        with:
          name: trevstack
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Install NPM Packages
        working-directory: ./client
        run: npm i && npm ci # https://github.com/npm/cli/issues/6787#issuecomment-2128344748
        
      - name: Update
        run: nix develop --command trevstack-update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          delete-branch: true
          title: Bump deps


